### ISSUE TITLE
Example Neuron -> CoreNeuron workflow

### ISSUE THREAD

**Issue by bcumming** [BlueBrain/CoreNeuron#1]
Congratulations with making the public release!

Have you got an example of a workflow for building a model in Neuron and exporting it to run in CoreNeuron?

A simple model would be good, and an example of building a larger network (out of simple cells/mechanisms) that tests CoreNeuron over multiple nodes would be even better!

**Comment by delalond** [comment]
Hi ben !

Thanks ! It was indeed quite an achievement !

At this point in time the code is compatible with the pcp benchmark data set. Future releases will address some of the current issues in terms of workflows. The schedule is not yet set for these future releases though.

We take note of your request and will try to release something that can address this issue.

Best regards,

Fabien



On 1 avr. 2016, at 11:13, Ben Cumming <notifications@github.com<mailto:notifications@github.com>> wrote:


Congratulations with making the public release!

Have you got an example of a workflow for building a model in Neuron and exporting it to run in CoreNeuron?

A simple model would be good, and an example of building a larger network (out of simple cells/mechanisms) that tests CoreNeuron over multiple nodes would be even better!

-

**Comment by bcumming** [comment]
The PCP data sets are available to a very small group of people, and can't be publicly discussed. So without guidance on how to generate our own inputs, CoreNeuron isn't very useful for those in the community who don't have access to the PCP data sets.

**Comment by bcumming** [comment]
Has there been any progress on the publicly available test cases and benchmarks for CoreNeuron? It would be great to try it out!

**Comment by bcumming** [comment]
That was good timing! I asked just hours before the new update. Thanks.
