### ISSUE TITLE
Some synaptic events are being delivered with a delay of one timestep

### ISSUE THREAD

**Issue by brunomaga** [BlueBrain/CoreNeuron#10]
Hi Michal @nrnhines 

When looking at the `deliver_events(tm)` that is delivering events within `nt->_t` and `nt->_t+0.5*nt->_dt` or `tm`, I see now that events were added to the queue one timestep too late.

In practice they are delivered half time step ahead.
To reproduce the bug, simply add to `NetCvode::deliver_event(double til, NrnThread *nt)`:
```
if (tt>=0) //safe guard until https://github.com/BlueBrain/CoreNeuron/issues/9 is fixed
{   assert(tt >= til-0.5*nt->_dt && tt <=til);  }
```
This `assert` double checks that events in the queue are only meant to be delivered within the previous *half* timestep.

On a PCP Layer1 circuit (use same generation method as my previous ticket):
- Neuron 347 at time 0.65 will be looking to events to be delivered between 0.65 and 0.65+0.5*dt i.e. 0.6625;
- Yet the queue has an event with time 0.625, i.e one and a half steps behind, instead of the max allowed of half step;
- That is a `ProbGABAAB_EMS` (id 139) event that was added to the queue only at the very same time step by `net_cvode_instance->check_thresh(nt)` at `deliver_net_events(NrnThread *nt)` in `cvodestb.cpp`.
- This is wrong: if I'm not mistaken should have been added in the previous step at `nrn_fixed_step_lastpart(nth)` so that the `nrn_deliver_events` at the previous turn could capture it.

Thank you for looking into this.

**Comment by pramodk** [comment]
@brunomaga : whats the status of this?

**Comment by pramodk** [comment]
@brunomaga confirmed that he is not able to reproduce. Reopen if you this an issue.
