### ISSUE TITLE
Are there plans of Python bindings ?

### ISSUE THREAD

**Issue by wizmer** [BlueBrain/CoreNeuron#113]
Hi,
I'd like to know if you plan on releasing some python bindings for core neuron ?

Thanks

**Comment by pramodk** [comment]
@wizmer : currently we are linking coreneuron inside neuron as library (e.g. neurodamus toolchain). So idea is to use coreneuron from existing neuron bindings instead of creating new ones. Let me know if there are any specific use cases you are considering.
