### ISSUE TITLE
Flags for compilation with Intel compiler

### ISSUE THREAD

**Issue by bcumming** [BlueBrain/CoreNeuron#127]
Have you got some recommended flags for optimized builds with the Intel compiler?

For example, if using a XEON Broadwell or a KNL, what flags should I pass for `CMAKE_{CXX,C}_FLAGS`?

In your experience, is the Intel compiler the fastest, or are PGI/Cray equivalent/better?

**Comment by pramodk** [comment]
Hi Ben,

> recommended flags for optimized builds with the Intel compiler?
> For example, if using a XEON Broadwell or a KNL, what flags should I pass for CMAKE_{CXX,C}_FLAGS?

With O2, typically add `-xMIC-AVX512` for KNL and just `-xHost` while compiling on skylake nodes.

> In your experience, is the Intel compiler the fastest, or are PGI/Cray equivalent/better?

Honestly I haven't compared PGI vs Cray vs Intel for more than year...but I remember Cray compiler was bit aggressive for vectorisation and those state/current kernels were `bit` faster with Cray. But overall I don't expect much difference with typical kernels from mod2c.

**Comment by bcumming** [comment]
Thanks @pramodk!

You find that `-O2` gets better results than `-O3` in this case?

**Comment by pramodk** [comment]
On Skylake/KNL ? I don't remember precisely...but have used -O2 often because compiler  like Cray does some extra/unsafe optimisations with O3.

**Comment by bcumming** [comment]
Oh, yeah. When we supported XLC our CMake had to set flags to stop it from doing non-standard floating point optimizations.

Thanks for the help, I will close this now.
