### ISSUE TITLE
Matching MPI rank count in NEURON and CoreNeuron

### ISSUE THREAD

**Issue by bcumming** [BlueBrain/CoreNeuron#128]
The documentation states that if NEURON is used to generate CoreNeuron inputs, both must use the same number of MPI ranks.

Is this still a requirement?

I have noticed that for a ring benchmark I can run a model generated with `N` ranks on `M` ranks and get the expected `M/N` speedup and the same number of spikes (I haven't checked if the same spikes are generated yet.)

Do we have to use the same number of ranks so that the connection tables match up correctly? That would explain why the ring model still "works".

**Comment by nrnhines** [comment]
That is the case only in the direct communication mode. For the file communication mode the total
number of *_1.dat files is equal to the number of global threads used by CoreNEURON. Each of these
files is generated by a NEURON thread.  On the side of NEURON, in principle each file could be
generated by an independent process.

**Comment by bcumming** [comment]
Thanks for the information.

When you talk about global threads in CoreNEURON, do you mean the total number of OpenMP threads? And when you say NEURON thread, do you mean instances of `NrnThreaad` objects?

What if the number of `_1.dat` files is greater than the number of CoreNeuron threads, say there are two for every thread, will each OpenMP thread run two `NrnThread` objects (which if my memory serves me correctly, are groups of cell state)?

**Comment by nrnhines** [comment]
I meant the total number of NrnThread objects acrosss all mpi ranks. Pramod can weigh in with regard to OpenMP. I believe there is a one to one correspondence in CoreNEURON between NrnThread objects
and _1.dat files. That is established with the nrnfiles.dat file.
