### ISSUE TITLE
Remove pthread based multi-threading implementation

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#147]
Coreneuron inherits pthread based multi-threading code which is not used. This can be safely removed as we rely on OpenMP.

Todo : 

* codebase under `#if USE_PTHREAD` can be safely removed
* codebase under `#if (USE_PTHREAD || defined(_OPENMP))` should be changed to `#if defined(_OPENMP)`

**Comment by st4rl3ss** [comment]
Jenkins pipeline worked. Should be ready to be merged.

**Comment by st4rl3ss** [comment]
Solved and merged with #148
