### ISSUE TITLE
nrnivmodl-core should create static libcorenrnmech-0.0.a

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/CoreNeuron#149]
While trying to build a `special-core` for running in GPUs I came across the following error:
```
Failing in Thread:1
call to cuModuleGetGlobal returned error 500: Not found
```
It seems that PGI needs all the libraries to be linked statically and the only option of `nrnivmodl-core` is building the `special-core` dynamically.
There could be added an option in `nrnivmodl_core_makefile` to build the `special-core` either dynamically, statically, or both, so that if the simulation is needed to run on GPUs the executable can be built statically.

**Comment by olupton** [comment]
I think this is already done, we can certainly execute on GPU with PGI/NVHPC compilers.
