### ISSUE TITLE
Understanding units handing in MOD2C

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#151]
Understand how mod2c handles unit specification in MOD files : https://github.com/BlueBrain/mod2c/blob/master/src/mod2c_core/units.c 

@iomaganaris : will discuss detailed about this offline.

**Comment by iomaganaris** [comment]
Based on the mod2c handling of units, [units parsing capability](https://github.com/BlueBrain/nmodl/commit/1c9e65e413bdc77f367d12eb090a67528ea876a4) was added in `NMODL`
