### ISSUE TITLE
Use scope-like API for instrumentor

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/CoreNeuron#158]
Unless I am not mistaken, most of the `end` statements are in the same scope than the corresponding `begin`. So I suggest to use API that would leverages scopes like scoped_lock for instance.

Instead of:

```cpp
if (nrn_have_gaps) {
    Instrumentor::phase_begin("gap-v-transfer");
    nrnthread_v_transfer(_nt);
    Instrumentor::phase_end("gap-v-transfer");
}
```
have something like:

```cpp
if (nrn_have_gaps) {
    Instrumentor::phase p("gap-v-transfer");
    nrnthread_v_transfer(_nt);
}
```

**Comment by tristan0x** [comment]
This improvement comes from #156

**Comment by tapaswenipathak** [comment]
Hi @tristan0x, I read the occurrence of all such API usage, can I work on this?

**Comment by tristan0x** [comment]
I will ask @pramodk to perform the triage of the issues so that it is easier for you to know what you can do to help us. But yes, I think you can start implementing this. Do not hesitate to ask questions.
Thanks!

**Comment by tapaswenipathak** [comment]
I completed `Instrumentor` in my [fork branch](https://github.com/tapaswenipathak/CoreNeuron/tree/api). I'm writing [`Caliper`](https://github.com/BlueBrain/CoreNeuron/blob/master/coreneuron/nrniv/profiler_interface.h#L44-L56) using https://llnl.github.io/Caliper/AnnotationAPI.html#function-annotations then  `CUDA_PROFILING`, `Tau`, `CRAYPAT`. I think `NullInstrumentor` shouldn't have a implementation? Please let me know if I am missing anything.

**Comment by tapaswenipathak** [comment]
I completed `Instrumentor` in my [fork branch](https://github.com/tapaswenipathak/CoreNeuron/tree/api). I'm writing [`Caliper`](https://github.com/BlueBrain/CoreNeuron/blob/master/coreneuron/nrniv/profiler_interface.h#L44-L56) using https://llnl.github.io/Caliper/AnnotationAPI.html#function-annotations. Can you please let me know if  the implementation is required in  `CUDA_PROFILING`, `Tau`, `CRAYPAT` and `NullInstrumentor` as well. There is nearly no usage of these?

**Comment by tapaswenipathak** [comment]
I'm quite confused reading https://github.com/BlueBrain/CoreNeuron/blob/master/coreneuron/nrniv/profiler_interface.h#L44-L56, what else should be added? do you suggest adding a timer interface as for all profiler interface is already there.

**Comment by tapaswenipathak** [comment]
I'm quite confused reading https://github.com/BlueBrain/CoreNeuron/blob/master/coreneuron/nrniv/profiler_interface.h#L44-L56, what else should be added? do you suggest adding a timer interface as for all profiler interface is already there I think.

**Comment by tapaswenipathak** [comment]
I'm quite confused reading https://github.com/BlueBrain/CoreNeuron/blob/master/coreneuron/nrniv/profiler_interface.h, what else should be added? do you suggest adding a timer interface as for all profiler interface is already there I think. Are there any other functionalities I should add in profiler_interface?

**Comment by tapaswenipathak** [comment]
I'm quite confused reading https://github.com/BlueBrain/CoreNeuron/blob/master/coreneuron/nrniv/profiler_interface.h, are there any other functionalities I should add in profiler_interface? do you suggest adding a timer interface as for all profiler interface is already there I think.

**Comment by tristan0x** [comment]
> I completed `Instrumentor` in my [fork branch](https://github.com/tapaswenipathak/CoreNeuron/tree/api). I'm writing [`Caliper`](https://github.com/BlueBrain/CoreNeuron/blob/master/coreneuron/nrniv/profiler_interface.h#L44-L56) using https://llnl.github.io/Caliper/AnnotationAPI.html#function-annotations. Can you please let me know if the implementation is required in `CUDA_PROFILING`, `Tau`, `CRAYPAT` and `NullInstrumentor` as well. There is nearly no usage of these?

The new Instrumentor scoped API you need to write should be independent from the real implementation (Caliper, Tau, ...). This new `phase` C++ struct should call the `phase_begin` function in its constructor and `phase_end` in its destructor.

I read your change in your fork branch, few remarks:
* I cannot see the implementation of  `Instrumentor::phase` struct. Did you forget to push it?
* instances of this struct may be destructed as soon as `phase_end` may be called. For instance:

    ```c++
    // initialization and loading functions moved to separate
    {
        Instrumentor::phase p("load-model");
        nrn_init_and_load_data(argc, argv, !configs.empty());
    }

    std::string checkpoint_path = nrnopt_get_str("--checkpoint");
    if (strlen(checkpoint_path.c_str())) {
        nrn_checkpoint_arg_exists = true;
    }
    std::string output_dir = nrnopt_get_str("--outpath");

    if (nrnmpi_myid == 0) {
        mkdir_p(output_dir.c_str());
    }
    ```

    Instead of:
    ```c++
    // initialization and loading functions moved to separate
    Instrumentor::phase p("load-model");
    nrn_init_and_load_data(argc, argv, !configs.empty());

    std::string checkpoint_path = nrnopt_get_str("--checkpoint");
    if (strlen(checkpoint_path.c_str())) {
        nrn_checkpoint_arg_exists = true;
    }
    std::string output_dir = nrnopt_get_str("--outpath");

    if (nrnmpi_myid == 0) {
        mkdir_p(output_dir.c_str());
    }    ````
