### ISSUE TITLE
Is PG_ACC_BUGS still necessary?

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#169]
CoreNEURON  has following macros : 

```
→ grep -r ACC_BUG coreneuron/*
coreneuron/mech/modfile/hh.cpp:#if defined(PG_ACC_BUGS)
coreneuron/nrnoc/eion.cpp:#if defined(PG_ACC_BUGS)
coreneuron/nrnoc/register_mech.cpp:#if defined(PG_ACC_BUGS)
coreneuron/nrnoc/nrnoc_ml.h:#if PG_ACC_BUGS
```

Todo for this ticket : 

* Check when `PG_ACC_BUGS` was introduced and what was the purpose
* If it was due to some old version, check if the issue doesnt appear with current 18.4 PGI compiler
* If so, remove related code from CoreNEURON as well as MOD2C

**Comment by olupton** [comment]
This was removed in https://github.com/BlueBrain/CoreNeuron/pull/455.
