### ISSUE TITLE
Gapjunction in coreNeuron

### ISSUE THREAD

**Issue by 1601111315** [BlueBrain/CoreNeuron#17]
I want to simulate a network with gapjunctions on CoreNeuron. Every cell connect to two or more cells in this network. The "source_var" function in ParallelContext seems unable to make one cell connect to more than one cell. So I defined a POINTER in my nmodl file of gapjunction, and it can run on Neuron. but it cannot be compiled successfully by CoreNeuron. Could you please tell me what should I do to solve this problem? Thank you.

**Comment by nrnhines** [comment]
The intention is that there be no problem in a single source_var connecting to any number of target_var.
In fact the intention is that it be as general as is supported in NEURON. Perhaps there is a bug. I will
test a 2-d heart model that I have where, except at boundaries, each source connects to 4 targets.
Or, you may provide me with a zip file of al the NEURON files needed to run in NEURON and which
does not work properly when translated to CoreNEURON. Send to michael.hines@yale.edu

**Comment by pramodk** [comment]
@nrnhines @1601111315 : is this still an issue? If not we can close this.

**Comment by nrnhines** [comment]
We can close
