### ISSUE TITLE
Compile error when compiling CoreNeuron with PGI19.4 and CUDA10

### ISSUE THREAD

**Issue by 1601111315** [BlueBrain/CoreNeuron#175]
Hi all
I'm trying to compile CoreNeuron with PGI19.4 and CUDA10. My gcc version is 5.4.0 and cmake version is 3.14.3. Here are the commands I used to compile:

module load /path/to/pgi/modfile /path/to/pgi_mpi/modfile
export CC=mpicc
export CXX=mpicxx
cmake .. -DCMAKE_C_FLAGS:STRING="-O2 -lrt -ta=tesla:cuda10.0" \                                             
              -DCMAKE_CXX_FLAGS:STRING="-O2 -lrt -std=c++11 -ta=tesla:cuda10.0"\ 
              -DCOMPILE_LIBRARY_TYPE=STATIC\ 
              -DCMAKE_INSTALL_PREFIX=/path/toinstall\ 
              -DCUDA_HOST_COMPILER=`which gcc`\
              -DCUDA_PROPAGATE_HOST_FLAGS=OFF\ 
              -DENABLE_SELECTIVE_GPU_PROFILING=ON\ 
              -DENABLE_OPENACC=ON\
make

It raised following errors (only list two of them here):
"/home/Softwares/pgi19/linux86-64-llvm/19.4/include/edg/mmintrin.h", line 1267:
 error: argument of type "__v4hi" is incompatible with parameter of type "__attribute((vector_size(8))) short" 
return (__m64)__builtin_ia32_pcmpgtw((__v4hi)__m1, (__v4hi)__m2);

"/home/Softwares/pgi19/linux86-64-llvm/19.4/include/edg/mmintrin.h", line 1289: 
error: argument of type "__v2si" is incompatible with parameter of type "__attribute((vector_size(8))) int" 
return (__m64)__builtin_ia32_pcmpgtd((__v2si)__m1, (__v2si)__m2);

Error limit reached.
100 errors detected in the compilation of "/path/to/CoreNeuron/nrniv/balance.cpp".

Could you please have a look at it? Thank you.

**Comment by pramodk** [comment]
@1601111315 : I have seen similar issue with 19.4.

For time being, could you add ` -DR123_USE_SSE=0` to compiler flags?

**Comment by 1601111315** [comment]
I tried this, but it seems doesn't work. cmake command I use is as following:

cmake .. -DCMAKE_C_FLAGS:STRING="-O2 -lrt -ta=tesla:cuda10.0" \
-DCMAKE_CXX_FLAGS:STRING="-O2 -lrt -std=c++11 -ta=tesla:cuda10.0"\
-DCOMPILE_LIBRARY_TYPE=STATIC\
-DCMAKE_INSTALL_PREFIX=/path/toinstall\
-DCUDA_HOST_COMPILER=which gcc
-DCUDA_PROPAGATE_HOST_FLAGS=OFF\
-DENABLE_SELECTIVE_GPU_PROFILING=ON\
-DENABLE_OPENACC=ON\
-DR123_USE_SSE=0

**Comment by pramodk** [comment]
I meant adding that C/C++ flags and setting build type to custom:

```
cmake .. -DCMAKE_C_FLAGS:STRING="-O2 -lrt -ta=tesla:cuda10.0 -DR123_USE_SSE=0" 
-DCMAKE_CXX_FLAGS:STRING="-O2 -lrt -std=c++11 -ta=tesla:cuda10.0 -DR123_USE_SSE=0"
-DCOMPILE_LIBRARY_TYPE=STATIC
-DCMAKE_INSTALL_PREFIX=/path/toinstall
-DCUDA_HOST_COMPILER=which gcc
-DCUDA_PROPAGATE_HOST_FLAGS=OFF
-DENABLE_SELECTIVE_GPU_PROFILING=ON
-DENABLE_OPENACC=ON
-DCMAKE_BUILD_TYPE=CUSTOM
```

**Comment by 1601111315** [comment]
Thank you. It also doesn't work and I got the same errors.

**Comment by 1601111315** [comment]
Is it because of GPU? Here the GPU on the server is tesla v100. I have successfully installed CoreNeuron with PGI19.4 on a machine with tesla k80 GPU.

**Comment by pramodk** [comment]
We also have volta GPUs. Could you verify if `-DR123_USE_SSE=0` is being added to compilation flags?. If you could provide partial output of `make VERBOSE=1`, it will be great!

My complete build script on our system was:

```
git clone --recursive https://github.com/BlueBrain/CoreNeuron.git coreneuron
cd coreneuron
mkdir -p build && cd build

module load pgi/19.4 cuda/9.2.88 hpe-mpi cmake
export CC=mpicc
export CXX=mpicxx

cmake .. \
    -DCMAKE_C_FLAGS="-O2 -ta=tesla:cuda9.2 -DR123_USE_SSE=0" \
    -DCMAKE_CXX_FLAGS="-O2 -ta=tesla:cuda9.2 -DR123_USE_SSE=0" \
    -DCOMPILE_LIBRARY_TYPE=STATIC  \
    -DCUDA_HOST_COMPILER=`which gcc` \
    -DCUDA_PROPAGATE_HOST_FLAGS=OFF \
    -DENABLE_SELECTIVE_GPU_PROFILING=ON \
    -DENABLE_OPENACC=ON \
    -DAUTO_TEST_WITH_SLURM=OFF \
    -DAUTO_TEST_WITH_MPIEXEC=OFF \
    -DFUNCTIONAL_TESTS=OFF \
    -DUNIT_TESTS=OFF
make VERBOSE=1 -j12
```

**Comment by 1601111315** [comment]
Here is my complete build script:
```
rm -rf build                                                                                                                                                                                                                                               
mkdir build
cd build
module purge
module load /home/zyc/Softwares/pgi19/modulefiles/pgi/19.4 \
/home/zyc/Softwares/pgi19/modulefiles/openmpi/3.1.3/2019
export CC=mpicc
export CXX=mpicxx
cmake .. \ 
        -DCMAKE_C_FLAGS:STRING="-O2 -lrt -DR123_USE_SSE=0" \
        -DCMAKE_CXX_FLAGS:STRING="-O2 -lrt -std=c++11 -DR123_USE_SSE=0" \
        -DCOMPILE_LIBRARY_TYPE=STATIC \
        -DCMAKE_INSTALL_PREFIX=/home/zyc/Softwares/GPU-Neuron/install \
        -DCUDA_HOST_COMPILER=`which gcc`  \
        -DCUDA_PROPAGATE_HOST_FLAGS=OFF \ 
        -DENABLE_SELECTIVE_GPU_PROFILING=ON \ 
        -DENABLE_OPENACC=ON \
        -DAUTO_TEST_WITH_SLURM=OFF \
        -DAUTO_TEST_WITH_MPIEXEC=OFF \
        -DFUNCTIONAL_TESTS=OFF \
        -DUNIT_TESTS=OFF \
        -DCMAKE_BUILD_TYPE=CUSTOM
make VERBOSE=1
```

And here are compile information and errors (only list the first one), I hope that they are useful:
```
[27%]Building CXX object coreneuron/CMakeFiles/coreneuron.dir/nrniv/balance.cpp.o
cd /home/zyc/Softwares/GPU-Neuron/sources/CoreNeuron_new/build/coreneuron && /home/zyc/Softwares/pgi19/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpicxx  -DCORENEURON_BUILD -DCUDA_PROFILING -DDISABLE_HOC_EXP -DENABLE_SPLAYTREE_QUEUING -DHAVE_MALLOC_H -DLAYOUT=0 -DNRNMPI=1 -DPG_ACC_BUGS -DSWAP_ENDIAN_DISABLE_ASM -I/home/zyc/Softwares/GPU-Neuron/sources/CoreNeuron_new/coreneuron/utils/randoms -I/home/zyc/Softwares/GPU-Neuron/sources/CoreNeuron_new/build/coreneuron -I/home/zyc/Softwares/GPU-Neuron/sources/CoreNeuron_new -I/home/zyc/Softwares/GPU-Neuron/sources/CoreNeuron_new/coreneuron -I/usr/local/cuda/include  -acc -Minline=size:200,levels:10 -O2 -lrt -std=c++11 -ta=tesla:cuda9.2 -DR123_USE_SSE=0 -mp  -fPIC   --c++11 -A -o CMakeFiles/coreneuron.dir/nrniv/balance.cpp.o -c /home/zyc/Softwares/GPU-Neuron/sources/CoreNeuron_new/coreneuron/nrniv/balance.cpp
"/home/zyc/Softwares/pgi19/linux86-64-llvm/19.4/include/edg/mmintrin.h", line
          85: error: argument of type "__v2si" is incompatible with parameter
          of type "__attribute((vector_size(8))) int"
      return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
```

**Comment by pramodk** [comment]
@1601111315 : could you try to disable other assembly targets?You can see [here](https://github.com/BlueBrain/CoreNeuron/blob/5af3a6f11f332b45b5aba8259f4bf56dcdfde306/coreneuron/utils/randoms/Random123/features/pgccfeatures.h#L79) the assembly targets that Random123 uses internally. For example, adding following flags:

```
-DR123_USE_AES_NI=0 -DR123_USE_SSE4_2=0 -DR123_USE_SSE4_1=0
```

I will take a detailed look later this week.

**Comment by 1601111315** [comment]
I disabled these targets, unfortunately it also doesn't work. Here is the compile information
```
cd /home/zyc/Softwares/GPU-Neuron/sources/CoreNeuron/build/coreneuron && /home/zyc/Softwares/pgi19/linux86-64-llvm/2019/mpi/openmpi-3.1.3/bin/mpicxx  -DCORENEURON_BUILD -DCUDA_PROFILING -DDISABLE_HOC_EXP -DENABLE_SPLAYTREE_QUEUING -DHAVE_MALLOC_H -DLAYOUT=0 -DNRNMPI=1 -DPG_ACC_BUGS -DSWAP_ENDIAN_DISABLE_ASM -I/home/zyc/Softwares/GPU-Neuron/sources/CoreNeuron/coreneuron/utils/randoms -I/home/zyc/Softwares/GPU-Neuron/sources/CoreNeuron/build/coreneuron -I/home/zyc/Softwares/GPU-Neuron/sources/CoreNeuron -I/home/zyc/Softwares/GPU-Neuron/sources/CoreNeuron/coreneuron -I/usr/local/cuda/include  -acc -Minline=size:200,levels:10 -O2 -lrt -std=c++11 -ta=tesla:cuda9.2 -DR123_USE_SSE=0 -DR123_USE_AES_NI=0 -DR123_USE_SSE4_2=0 -DR123_USE_SSE4_1=0 -DR123_USE_SSE=0 -DR123_USE_AES_OPENSSL=0 -DR123_USE_GNU_UINT128=0 R123_USE_ASM_GNU=0 -DR123_USE_CPUID_MSVC=0 -DR123_USE_X86INTRIN_H=0 -DR123_USE_IA32INTRIN_H=0 -DR123_USE_XMMINTRIN_H=0 R123_USE_EMMINTRIN_H=0 -DR123_USE_SMMINTRIN_H=0 -DR123_USE_WMMINTRIN_H=0 -DR123_USE_INTRIN_H=0 -DR123_USE_MULHILO32_ASM=0 -DR123_USE_MULHILO64_MULHI_INTRIN=0 -DR123_USE_MULHILO64_ASM=0 -DR123_USE_MULHILO64_MSVC_INTRIN=0 -DR123_USE_MULHILO64_CUDA_INTRIN=0 -DR123_USE_MULHILO64_OPENCL_INTRIN=0 -mp  -fPIC   --c++11 -A -o CMakeFiles/coreneuron.dir/nrniv/balance.cpp.o -c /home/zyc/Softwares/GPU-Neuron/sources/CoreNeuron/coreneuron/nrniv/balance.cpp

"/home/zyc/Softwares/pgi19/linux86-64-llvm/19.4/include/edg/mmintrin.h", line
          85: error: argument of type "__v2si" is incompatible with parameter
          of type "__attribute((vector_size(8))) int"
      return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
... (other similar errors)
Error limit reached.
100 errors detected in the compilation of "/home/zyc/Softwares/GPU-Neuron/sources/CoreNeuron/coreneuron/nrniv/balance.cpp".
Compilation terminated.

```

**Comment by 1601111315** [comment]
It seems because of the version of cmake. There is no error when I compile with cmake 3.8.2
