### ISSUE TITLE
Issues running the ringtest example 

### ISSUE THREAD

**Issue by SteMasoli** [BlueBrain/CoreNeuron#183]
Hi.

I couple of years back, using the script in this page, https://github.com/nrnhines/ringtest ,  i was able to run some test with CoreNeuron.

The last version of the script works except the CoreNeuron step.

1) To run ringtest i had to change the executable location from "bin" to "apps".
./coreneuron_x86/**bin**/coreneuron_exec -e 100 -d coreneuron_data

2) Running the previous command generates this error.
coreneuron_exec: /coreneuron_new/sources/CoreNeuron/coreneuron/nrniv/nrn_setup.cpp:1747: void coreneuron::read_phase2(coreneuron::FileHandler&, int, coreneuron::NrnThread&): Assertion `ps->gid_ > -1' failed.
Aborted

**Comment by pramodk** [comment]
@SteMasoli  : could you tell us NEURON version that you are using?

**Comment by SteMasoli** [comment]
@pramodk The version is the latest developmental code automatically installed with the CoreNeuron script.

**Comment by pramodk** [comment]
@st4rl3ss : could you take a look at ringtest, run it locally/bb5 and test?

**Comment by nrnhines** [comment]
I bellieve the bug is fixed with the latest changeset 78d1fe7cf

**Comment by pramodk** [comment]
thank you Michael. @iomaganaris  has tested latest neuron and it's working fine now.

**Comment by SteMasoli** [comment]
Thank you.
I have just tested it and everything is fine on my machine too.
