### ISSUE TITLE
Add clang-format target based on hpc-conding-convetion tools

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#200]
Currently we are using ClangFormatHelper.cmake and ClangFormatUtils.cmake for doing code formatting. This should be based on https://github.com/BlueBrain/hpc-coding-conventions/tree/master/cpp/formatting

**Comment by pramodk** [comment]
being done in #365

**Comment by olupton** [comment]
I think this was done in https://github.com/BlueBrain/CoreNeuron/pull/465.
