### ISSUE TITLE
Refactor nrn_setup.cpp

### ISSUE THREAD

**Issue by ohm314** [BlueBrain/CoreNeuron#241]
Currently `nrn_setup.cpp` is a ~2300 line file with several very long, complicated functions (e.g. `read_phase2`). This code is very hard to understand and maintain. We need to:

* get a clear understanding of all functions in this module
* Split the function further down into smaller functions that do single simple operations
* Simplify the code, make variable naming clearer, refactor to reduce code duplication

This will also be important for the rest of the refactoring as currently many of the data structures of coreneuron are touched here in the context of these functions and it is hard to rewrite the rest of the code ensuring that specifically in this location nothing breaks.

**Comment by alkino** [comment]
Fixed by #283
