### ISSUE TITLE
Can the simulation workflow be simplified?

### ISSUE THREAD

**Issue by Helveg** [BlueBrain/CoreNeuron#270]
I'm reading through the README of [this](https://github.com/nrnhines/ringtest) repository which was recommended as a basic tutorial, but it seems quite advanced and complicated to start a network that was constructed using NEURON's Python interface.

Wouldn't it be a better user experience if we could run arbitrary python code to construct the network, and have CoreNeuron analyse what NEURON components have been constructed at the end of the script, then construct these in CoreNeuron and run the optimised CoreNeuron simulation?

I guess that would make CoreNeuron as simple to use as:

```
coreneuron my_complex_network.py
```

(barring all of the standard flags and MPI things)

What are the obstacles to this approach?

**Comment by pramodk** [comment]
@Helveg : I completely agree with your suggestion. In fact we are working on making the usage of CoreNEURON completely transparent for existing NEURON users. For example, see the [example in tests](https://github.com/BlueBrain/CoreNeuron/blob/master/tests/jenkins/neuron_direct.py) directory. In that example NEURON invokes CoreNEURON using:

```python
pc.nrncore_run("-e %g"%h.tstop, 0)
```

We want to eliminate above call as well and control to use of CoreNEURON using single flag.

There is some additional work required and we will start that soon. This is why the README is not updated and still showing "old style" use of CoreNEURON. Sorry for that.

> @alexsavulescu : this is something to look at next (coming weeks)

**Comment by pramodk** [comment]
Hello @Helveg,

We have completely refactored simulation workflow with NEURON+CoreNEURON. You can see now [updated instructions in README](https://github.com/BlueBrain/CoreNeuron#installation) file. If you have any questions, we will be happy clarify.

**Comment by pramodk** [comment]
thanks, I have fixed that!
