### ISSUE TITLE
CI should test NMODL internal/external build with sympy based solvers

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#281]
To avoid issues reported in #276 and #278, we should update CI to test
* Internal and external NMODL
* sympy based solvers (non-cnexp solvers)
* ISPC backend

**Comment by olupton** [comment]
The GitLab CI uses external NMODL and includes both `+sympy` and `~sympy` variants: https://github.com/BlueBrain/CoreNeuron/blob/d6507e20ffdcf652b07e231347174f8f9c89e32a/.gitlab-ci.yml#L126

The GitHub CI uses internal NMODL and includes both ISPC and C++ variants: https://github.com/BlueBrain/CoreNeuron/blob/d6507e20ffdcf652b07e231347174f8f9c89e32a/.github/workflows/coreneuron-ci.yml#L39-L41
