### ISSUE TITLE
Integrate tqperf model under Jenkins CI

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#287]
https://github.com/nrnhines/tqperf is good spike exchange test as it stresses MPI communication. We should integrate it under Jenkins Pipeline.

* The instructions  to run the model are [here](https://github.com/BlueBrain/CoreNeuron/pull/273#issuecomment-612804717).

~Note that we are using pramodk/tqperf fork as we are waiting for https://github.com/nrnhines/tqperf/pull/2 to be merged.~

**Comment by alkino** [comment]
Where should I include it?
New job or existing one?

**Comment by pramodk** [comment]
It should be in existing Jenkinsfile as a new stage. @iomaganaris can help / clarify if anything needed.

**Comment by alkino** [comment]
#288

**Comment by alkino** [comment]
Done
