### ISSUE TITLE
Remove code related to model duplication factor  (-z,--multiple, -x,--extracon command line argument)

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#291]
In the old days we wanted to duplicate input model by certain factor to perform scaling studies. Now models are quite bigger. We have ability to generate arbitrary size models to perform scaling studies.

In order to reduce the code complexity, I would suggest to remove the code related to model duplication from coreneuron.

@nrnhines : would that be ok? I haven't used this for few years already and don't see any use cases now days.

**Comment by alkino** [comment]
i take it, I will be so happy to remove extracon !!

**Comment by alkino** [comment]
You know it is not so hard and can be done in #283 
Only waiting for @nrnhines advices about it is safe or not

**Comment by pramodk** [comment]
@alkino : #283 is done, so this can be done now.
