### ISSUE TITLE
InterleaveInfo breaks rule of 3 (5)

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/CoreNeuron#3]
By pure chance, I came across class [`InterleaveInfo`](https://github.com/BlueBrain/CoreNeuron/blob/ba1fc53e2cd6fe8ac06e9afeba9b7504035f7fb8/coreneuron/nrniv/cellorder.h#L9), which seems to do some resource management. Its [destructor releases a host of resources via `delete[]`](https://github.com/BlueBrain/CoreNeuron/blob/ba1fc53e2cd6fe8ac06e9afeba9b7504035f7fb8/coreneuron/nrniv/cellorder.cpp#L36), however, no special care is taken of copy construction or assignment, which could result in memory errors at runtime (specifically, double-deletes, but formally, undefined behaviour.) I suggest either making the class non-copyable, or implementing the correct copy and assignment semantics.

---

See [the rule of three/five/zero](http://en.cppreference.com/w/cpp/language/rule_of_three).

**Comment by pramodk** [comment]
Sorry, didn't get time to look into this before due to other stuff. Addressed in #22.
