### ISSUE TITLE
Some errors occur when building coreneuron with GPU support

### ISSUE THREAD

**Issue by xiupingcui** [BlueBrain/CoreNeuron#301]
Hello, 
   When I build coreneuron with gpu version, some errors happen, and I don't know why.
   The error like this occurs:
![image](https://user-images.githubusercontent.com/41467756/81468040-8dd60680-920f-11ea-8bc7-767190067e8b.png)
  The error is  "undefined reference to `operator delete[](void*, unsigned long)'", and it seems that it's because of something wrong with ld.
  My linux is centos7, gcc/g++ version is  7.3, openmpi 3.1.3 (downloaded with pgi), pgi 19.10, cuda 10.0
The following is my cmake result
![image](https://user-images.githubusercontent.com/41467756/81468229-d510c700-9210-11ea-97d3-d94b791ce57e.png)
![image](https://user-images.githubusercontent.com/41467756/81468237-e5c13d00-9210-11ea-93e5-deebcc0a7d11.png)

  Do you have any idea why the error happened? 
  Thank you very much!

**Comment by pramodk** [comment]
@xiupingcui : May be your description wasn’t posted somehow?

**Comment by xiupingcui** [comment]
> @xiupingcui : May be your description wasn’t posted somehow?

Sorry, it seems that some network problem occurs, and now I post my description, thank you very much!

**Comment by pramodk** [comment]
@xiupingcui : thanks for reporting the issue!

 Even if you have  `GCC v7.3`, I suspect your default GCC on system is old i.e. `4.8.5`. The PGI compiler will use this old GCC by default. In your first screenshot you can see the path `/usr/include/c++/4.8.5`!

In order to solve this issue, we have to tell PGI compiler to use newer using following command:

```
# replace paths to PGI and GCC based on your system

/opt/pgi/linux86-64/19.10/bin/makelocalrc /opt/pgi/linux86-64/19.10/bin -gcc /path/to/gcc-7.3.0/bin/gcc -gpp /path/to/gcc-7.3.0/bin/g++ -g77 /path/to/gcc-7.3.0/bin/gfortran -x
```
You can see relevant discussion on PGI forum [here](https://www.pgroup.com/userforum/viewtopic.php?t=4664&sid=0a63c9aca1273976b6273bbd8d7dbba0).

Please let me know if this issue persist.

**Comment by xiupingcui** [comment]
OK, the problem is solved. Thank you very much, the reason is exactly what you pointed out.
However, when I run` nrniv-core -e 10 -d coreneuron_data --gpu --cell_permute=1`, another error occur, and I don't know if it is because I build the project in the wrong way.

**Comment by pramodk** [comment]
Ok great!

The second error is because we have built CoreNEURON with MPI enabled but we didn't use mpirun to start coreneuron. Could you try:

```
mpirun -n 1 nrniv-core -e 10 -d coreneuron_data --gpu --cell_permute=1 --mpi
```

Make sure to use `mpirun` from openmpi that you used in case there are multiple MPIs installed.

**Comment by xiupingcui** [comment]
Great! It works, and I think it is right now! Thank you very much!
BTW.  Is there any realistic neuron dataset now that can be directly used by coreneuron like ringtest?

**Comment by pramodk** [comment]
The goal with CoreNEURON is to support any NEURON model with little to no changes (e.g. some minor adjustments needed for thread safety, POINTER variables in MOD files).

So if you have any NEURON model, you could try that with CoreNEURON.

We are using internally using CoreNEURON for large number of simulations at scale (CPU/KNLs,  not GPU yet).  But I must admit that until now we haven't really put efforts on preparing sample models and documents everything as a step-by-step guide. Currently we are working on integration of CoreNEURON with NEURON and then we will focus on the documentation aspects and preparing sample models. (there are [samples around ](https://github.com/pramodk/nrntraub/tree/icei), but we need to document the instructions to run them via CoreNEURON).

But if you have any issues while running or testing your model, we will be happy to help.

**Comment by pramodk** [comment]
@xiupingcui : as original error was fixes, we can close this ticket now?

**Comment by xiupingcui** [comment]
Yes. I am sorry that I forgot that. Thank you very much!
