### ISSUE TITLE
Run coreneuron MOD file functional tests on GPU as well

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#308]
Currently https://github.com/nrnhines/testcorenrn is run only for CPUs. We need to run these tests for GPUs as well. See https://github.com/BlueBrain/CoreNeuron/blob/e7934b0eaf66ebba81e38b35b2c8b3833cd5ab96/tests/jenkins/Jenkinsfile#L188

[Readme](https://github.com/pramodk/testcorenrn/blob/master/readme) is not updated with the script that needs to be run under CI.

**Comment by olupton** [comment]
With https://github.com/neuronsimulator/nrn/pull/1019 then the NEURON CTest suite knows how to run these tests, including on GPUs. To address this issue we still need to add CI configuration to actually run those tests on a GPU node.

**Comment by olupton** [comment]
This was done in https://github.com/BlueBrain/CoreNeuron/pull/510.
