### ISSUE TITLE
nrnivmodl-core with NMODL uses nmodl executable from build dir

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/CoreNeuron#318]
When `nrnivmodl_core_makefile` is installed it still uses the `nmodl` executable which is on the build directory.
For example:
```
# Binary of MOD2C/NMODL depending on what was activated
ifeq (FALSE, TRUE)
    nmodl_binary_path = $(if $(NMODL_BINARY),$(NMODL_BINARY), /Users/magkanar/CoreNeuron/build/bin/nmodl)
else
    nmodl_binary_path = $(if $(NMODL_BINARY),$(NMODL_BINARY), $(bindir)/nmodl)
endif
```
I believe that this should change and point to the `nmodl` executable from the install directory.
Same for the nmodl python library.

**Comment by olupton** [comment]
The relevant code now seems to be
https://github.com/BlueBrain/CoreNeuron/blob/8b9213cdc2072d8d1bc8ef7ca5ff4504acfd89b3/extra/nrnivmodl_core_makefile.in#L101-L108 and
https://github.com/BlueBrain/CoreNeuron/blob/8b9213cdc2072d8d1bc8ef7ca5ff4504acfd89b3/CMakeLists.txt#L254-L255
but I'm not sure I see a problem, apart from an aesthetic one:
- if NMODL is installed externally then we take the `ifeq` branch and use `${nmodl_BINARY}`, which should be an installed location.
- if NMODL is built internally then we take the `else` and ultimately (I think) use `nmodl` from the same directory as `nrnivmodl-core`.
