### ISSUE TITLE
Extracellular potential and Local Field Potential [LFP]

### ISSUE THREAD

**Issue by pmoolchand** [BlueBrain/CoreNeuron#322]
@pramodk @nrnhines 

Is extracellular mechanism supported in CoreNeuron? And does CoreNeuron have a method for calculating LFP online?

**Comment by nrnhines** [comment]
The extracellular mechanism does not exist in CoreNEURON. However, one can ask to calculate i_membrane and from that calculate the LFP. Both NEURON and CoreNEURON have the notion of https://www.neuron.yale.edu/neuron/static/py_doc/simctrl/cvode.html#CVode.use_fast_imem
@pramodk will likely be able to point you to documentation and an example of calculationg LFP within CoreNEURON.  The advantage over extracellular mechanism in NEURON is that it is much faster and works during parallel simulations with variable step methods.
