### ISSUE TITLE
nrnivmodl-core generates a folder named x86_64/core

### ISSUE THREAD

**Issue by nrnhines** [BlueBrain/CoreNeuron#328]
Wouldn't the name corenrn be better so as not to conflict with coredump names.
Also a folder x86_64/x86_64 is generated but is empty.

**Comment by pramodk** [comment]
> Wouldn't the name corenrn be better so as not to conflict with coredump names.

agree!

> Also a folder x86_64/x86_64 is generated but is empty.

I haven't seen that. Does that happen always? I have:

```
→ ls -l ~/workarena/repos/bbp/modeldb-bulb3d/sim/x86_64/
total 328
drwxr-xr-x  4 kumbhar  10067     128 Jun 28 17:54 core
-rw-r--r--  1 kumbhar  10067       0 Jun 28 17:54 coreneuron.optrpt
-rw-r--r--  1 kumbhar  10067       0 Jun 28 17:54 ipo_out.optrpt
-rwxr-xr-x  1 kumbhar  10067  134124 Jun 28 17:54 libcorenrnmech.dylib
-rw-r--r--  1 kumbhar  10067     105 Jun 28 17:54 nrnivmodl_options.txt
-rwxr-xr-x  1 kumbhar  10067   27176 Jun 28 17:54 special-core
drwxr-xr-x  3 kumbhar  10067      96 Jun 28 17:54 special-core.dSYM
```

**Comment by nrnhines** [comment]
My mistake, looks like x86_64/x86_64 is coming from the cmake version of ```nrnivmodl .``` (which is still  retranslatinng and compileing all mod files every time it is run).
