### ISSUE TITLE
neuron-coreneuron voltage trajectory recording & update with GPU execution (Part I)

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#331]
Hello Michael,

From my understanding, we have NEURON-CoreNEURON variable trajectory recording but we haven't tested / implemented this for GPU execution, right?

If you could point the relevant sections in coreneuron where this recording happens, we can implement necessary code to copy buffers from GPU to CPU.

cc: @iomaganaris

**Comment by nrnhines** [comment]
GPU trajectory recording has not been implemented. See the TrajectoryRequests structure in multicore.hpp. The gpu needs to make available to the cpu the
```
    double** gather;  /* pointers to values that get scattered to NEURON */`
```

The cpu relevant code is in coreneuron/sim/fadvance_core.c in the function
```
void nrncore2nrn_send_values(NrnThread* nth) {
```

**Comment by pramodk** [comment]
For voltages we have partially achieved this in #357. For generic implementation, we will create separate ticket.

**Comment by olupton** [comment]
Closing as it was marked 'done' above.
