### ISSUE TITLE
multiple folders for nrnivnmodl-core

### ISSUE THREAD

**Issue by cattabiani** [BlueBrain/CoreNeuron#336]
Right now, in neuron, it is possible to chain folders and files in the call:

`nrnivmodl folder1 folder2 ...`

This is not (yet) possible in coreneuron. It would be useful (at least for me) to have the same functionality with nrnivmodl-core too

**Comment by pramodk** [comment]
With new workflow [described here](https://github.com/BlueBrain/CoreNeuron/blob/89b9f93557181e3e532cf59dbd09bfb50680ba63/README.md), we are adding coreneuron support directly in nrnivmodl as:

```
nrnivmodl -coreneuron mod-dir
````

Implemented in https://github.com/neuronsimulator/nrn/pull/707

**Comment by pramodk** [comment]
As we are moving to neuron workflow, this is not required.
