### ISSUE TITLE
Add minimal documentation about using CoreNEURON with NEURON

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#337]
As part of NEURON documentation here : https://neuronsimulator.github.io/nrn/py_doc/index.html

We should CoreNEURON sub-section describing:

* How to build CoreNEURON inside NEUERON (CMake Options); recommend to use Intel compiler; mention NMODL option as well but say that it's still beta / under development;
* Add simple example of python to run with in-memory mode : https://github.com/neuronsimulator/nrn/tree/master/test/coreneuron
* Also show hoc example for the same : https://github.com/neuronsimulator/nrn/tree/master/test/coreneuron
* Add section about running on GPU

**Comment by iomaganaris** [comment]
Added first draft of documentation in https://github.com/neuronsimulator/nrn/tree/docs/coreneuron

**Comment by pramodk** [comment]
@iomaganaris : seems like you added documentation but PR is not created or it's not appearing in the https://neuronsimulator.github.io/nrn/index.html ?

**Comment by iomaganaris** [comment]
@pramodk You're right. I think there was no PR for this. Will do now

**Comment by iomaganaris** [comment]
https://github.com/neuronsimulator/nrn/pull/912
This is now merged
