### ISSUE TITLE
Accessing recorded spikes via direct memory interface with NEURON

### ISSUE THREAD

**Issue by iraikov** [BlueBrain/CoreNeuron#340]
Hello,
Is it currently possible to access the recorded spikes from within the direct memory interface with NEURON? This would be very convenient for parallel optimizations where different parameter instantiations of the same cell(s) are simulated on different ranks, and writing/reading the spike times to and from files for each evaluation would not be practical. Thanks!

**Comment by pramodk** [comment]
Yeah agree! Currently we read-in generated `out.dat` but that will be generated by all ranks together. 

@nrnhines : Would it be possible to add new API to transfer spikes from CoreNEURON to NEURON so that `pc.spike_record` would work transparently for NEURON as well as CoreNEURON?

**Comment by nrnhines** [comment]
That is certainly possible and desirable. Spike transfer back from CoreNEURON to NEURON is one of the three next major steps for direct mode integration. The other two being transfer of all state data back to NEURON at the end of a CoreNEURON solve, and the inverse of that to allow NEURON to modify state after a CoreNEURON run and restart CoreNEURON to continue the run without rebuilding the CoreNEURON data structures.  For the latter it would be beneficial to support the appropriate grain level for amount of transfer. ie. ranging from a single parameter value, to the entire state. It remains to be seen whether NEURON can just begin to use the CoreNEURON data directly rather than maintaining a copy but I think that is promising.

Anyway, for spikes, at the risk of being a bit of a "hack" prior to a complete API design, one would have to create a new method
```
ParallelContext.nrncore_spike_transfer(spiketimevec, gidvec)
```
which would do the job.  I suppose we could use the neuron.coreneuron module to present this to the user but the implementation is a bit more indirect from a developer perspective and as on the foggy horizon there seem to be many images of other desireable methods, it may be useful to have an API discussion sooner rather than later.

**Comment by iraikov** [comment]
Hi @nrnhines @pramodk thanks for your comments. My understanding of the CoreNEURON direct memory test in the NEURON repository was that any vector recording a state variable in a section would get transferred to NEURON at the end of the simulation. This would appear to be the most seamless interface from a user's perspective. Having to explicitly call nrncore_spike_transfer would be slightly more overhead but would be ok as long as we can clear the spike recording vectors prior to starting a new simulation in the context of an optimization loop. (But I am guessing CoreNEURON already clears all recording vectors at the beginning of a simulation). The ability to stop and restart CoreNEURON would be very useful indeed, also for things like checkpoining and hotstart, but this is perhaps somewhat independent of shared memory buffers.

**Comment by pramodk** [comment]
Michael can comment on the other parts 

>  This would appear to be the most seamless interface from a user's perspective. Having to explicitly call nrncore_spike_transfer would be slightly more overhead

I agree with this! I don't know all  implementation aspects from NEURON but I  would also prefer to not have different API for coreneuron. 

> The ability to stop and restart CoreNEURON would be very useful indeed, also for things like checkpoining and hotstart, but this is perhaps somewhat independent of shared memory buffers.

:+1: We kind of "ignored" integration aspects with NEURIN for quite some time. But we are starting on this now. So hopefully we will get these use cases implemented soon.

By the way, if you haven't noticed, this is how current in-memory  transfer usage looks like:
* https://github.com/neuronsimulator/nrn/blob/master/test/coreneuron/test_direct.py
* https://github.com/neuronsimulator/nrn/blob/master/test/coreneuron/test_direct.hoc

**Comment by nrnhines** [comment]
A NEURON + CoreNEURON direct API is actually more useful than I thought as getting several minds involved is likely to produce something better than the first thing that comes to mind. E.g. the ```ParallelContext.nrncore_spike_transfer(spiketimevec, gidvec)``` idea will certainly work. But one of the contextual details is that  NEURON and CoreNEURON both know that they are participating in direct communication. So perhaps CoreNEURON should just turn off its creating an ```out.dat``` file and send back the spikes to the vectors that would have recorded them in a normal ```pc.solve(tstop)```. One nice side effect is that existing models that have an elaborate sequence of psolve followed by distributed parallel sorted output of spikes generated during the last psolve will _just work_ when the simulation is integrated by CoreNEURON.

**Comment by iraikov** [comment]
@nrnhines This sounds very general indeed. When you say the CoreNEURON will "send back" the spikes, does that mean that they will be stored in ParallelContext on the NEURON side, and then they can be retrieved at any time after the end of simulation? If yes, then I agree this will enable all sorts of complex workflows.

**Comment by nrnhines** [comment]
No. It means the spikes are stored in the two hoc Vector instances that are used in a non-coreneuron simulation. ie. ideally
https://www.neuron.yale.edu/neuron/static/py_doc/modelspec/programmatic/network/parcon.html#ParallelContext.spike_record in its
```
pc.spike_record(-1, tvec, idvec)
```
form or the more cumbersome
https://www.neuron.yale.edu/neuron/static/py_doc/modelspec/programmatic/network/netcon.html#NetCon.record in its
```
nc.record(tvec, idvec, nc.srcgid)
```
form.

**Comment by iraikov** [comment]
I see, yes that would be the most seamless option indeed.

**Comment by nrnhines** [comment]
@pramod what do you think about turning off the writing of out.dat by default during direct transfer mode. Or else a
default
```
neuron.coreneuron.spikeout = False
```
which would turn it off if there were a --spikeout 0   or --no-spikeout option.. We may have to eventually escape from the use of launch args to properly handle the direct mode, especially if the direct mode has a lot of specific options.

**Comment by alexsavulescu** [comment]
Hi @iraikov, we've just added this feature (#354). Would you consider trying it and giving us some feedback?

**Comment by iraikov** [comment]
Hi @alexsavulescu thanks a lot! I will try it out and let you know how it goes.

**Comment by iraikov** [comment]
Hi @alexsavulescu thanks a lot! I will try it out and let you know how it goes.

**Comment by iraikov** [comment]
Hi @alexsavulescu now CoreNEURON does not seem able to load my mechanisms. (The same simulation works in the latest version of standard NEURON). Is there anything I can do to diagnose this error?

**Comment by alexsavulescu** [comment]
Hi @iraikov , could you provide some code to reproduce?

**Comment by iraikov** [comment]
Hi @alexsavulescu 
I just tried adding the line

h.soma.insert("nax")

to the test_spikes.py script, and CoreNEURON does not recognize any mechanism that is passed to insert.
I just ran the script with LD_DEBUG=all and it shows that it is loading nrnmech.so and the symbols that belong to the various mechanisms.

**Comment by pramodk** [comment]
@iraikov : similar to `nrnivmodl mod_directory`, did you do `nrnivmodl-core mod_directory` ?  when NEURON launch coreneuron, it looks for `x86_64/libcorenrnmech.so` file to load mechanisms for coreneuron.

(currently README file is completely outdated and we plan to revamp all documentation soon).

**Comment by iraikov** [comment]
Hi @pramodk thanks, I completely forgot about nrnivmodl-core! It can load the mechanisms now.

**Comment by iraikov** [comment]
Hi @alexsavulescu @pramodk transferring spike times appears to work, thanks for implementing this feature!
However, I inadvertently discovered that passing a dt argument to Vector.record causes a segmentation fault in CoreNEURON. Is this a known issue, or should I submit a separate ticket?

**Comment by nrnhines** [comment]
There was a recent bug fix for this in NEURON. As CoreNEURON likely inherited the earlier code, that is he best place to look first.

**Comment by iraikov** [comment]
Thanks @nrnhines  And separately it looks like recording from h._ref_t with dt argument in CoreNEURON does not transfer the vector back to NEURON. Is this a related issue?

**Comment by nrnhines** [comment]
I removed my comment shortly after making it. The NEURON fix
```
commit a2e12d3157c19c8fa44c31e0be9825d0af03bfb6
Author: nrnhines <michael.hines@yale.edu>
Date:   Mon Apr 27 12:58:42 2020 -0400
    v.record(_ref_var, DT) after h.frecord_init() restarted at t=0. (#502)
    Needs to restart at current time.
```
fixed incorrect recording. Not whether it is recorded at all. I believe the CoreNEURON recording
of ```h._ref_t``` works for the per dt case (no arg). It could be extended to the other cases but as those are event based it does not fit well with the current per dt transfer per step implementation in CoreNEURON. So will require non-trivial implementation.

**Comment by alexsavulescu** [comment]
I suggest to close this ticket and maybe open another one for feature request regarding `dt` recording.

**Comment by iraikov** [comment]
I see thanks! I can refactor my code to not use recording dt when CoreNEURON simulation is enabled. Thanks everyone for the work on this issue.

**Comment by iraikov** [comment]
Hello,
Earlier, I had tested this in NEURON/CoreNEURON compiled with gcc on Ubuntu; I thought I had tested with the Intel compiler as well, but when I use the same test script with NEURON/CoreNEURON compiled with icc, the spike vectors are empty after the CoreNEURON simulation is completed. Could anyone confirm that direct memory transfer for spike vectors works with Intel-compiled executable? Thanks!

**Comment by pramodk** [comment]
@iraikov : I don't expect any difference between Intel vs GCC for spike transfer.  Could you run this test and see if it's passing https://github.com/neuronsimulator/nrn/blob/master/test/coreneuron/test_spikes.py ?

Also, when you don't see spikes, I would be curious to see coreneuron stats output at the end of run which is something like :

```
 Simulation Statistics
 Number of cells: 1
 Number of compartments: 5
 Number of presyns: 1
 Number of input presyns: 0
 Number of synapses: 1
 Number of point processes: 2
 Number of transfer (gap) targets: 0
 Number of spikes: 2
 Number of spikes with non negative gid-s: 2
```

**Comment by iraikov** [comment]
@pramodk Nevermind, I had not pulled the latest NEURON source on the system where compiling with Intel, only CoreNEURON. All the relevant test scripts work now. Sorry about the noise!

**Comment by pramodk** [comment]
oh ok! no problem :)
