### ISSUE TITLE
Random123 in VERBATIM : Allow GPU built executable to run on CPU

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#345]
Currently, if Random123 is used in the mod file then GPU built binary can't be run on CPU. This limitation should be removed as it's often required to run code on CPU for debugging and performance comparison.

**Comment by olupton** [comment]
Some tests are disabled because of this issue. For example in https://github.com/neuronsimulator/nrn/pull/1019 the `gf` test from https://github.com/neuronsimulator/testcorenrn has to be explicitly configured not to run on the CPU in GPU-enabled builds.
