### ISSUE TITLE
Test multi-process execution on GPUs and find out performance issue

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#348]
Recently we have seen that when using multiple ranks per GPU we don't see any performance improvement.
We need to find out the reason for this by using small test example.

**Comment by pramodk** [comment]
The issue is related to CUDA MPS service not being active on the target nodes. One can use `nvidia-cuda-mps-control -d ` to start MPS service. Otherwise, wrapper script can be used instead of executable:

```bash
$ cat wrapper_special

#!/bin/bash

#enable mps
nvidia-cuda-mps-control -d > /dev/null 2>&1

# call actual binary
shift
./x86_64/special "$@"
```

**Comment by olupton** [comment]
[BBP-internal note: HELP-14142 may be of interest]
