### ISSUE TITLE
nrnivmodl-core can not translate gap.mod in the NEURON code.

### ISSUE THREAD

**Issue by ikitayama** [BlueBrain/CoreNeuron#363]
I'm checking the NMODL translator on JURECA at JSC, but I get:

```
$ nrnivmodl-core
./gap.mod
[INFO] Running make with params: ROOT=/p/project/cjzam11/kitayama1/opt/nrn-master MODS_PATH=.
 -> Generating x86_64/core/mod2c/_mod_func.cpp
 -> MOD2C gap.mod
Translating
 into x86_64/core/mod2c/gap.cpp
Notice: Use of POINTER is not thread safe.
cvode_emit=0 cvode_not_allowed=0
 -> Generating x86_64/core/mod2c/_kinderiv.h
diff: x86_64/core/mod2c/_mod_func.cpp: No such file or directory
Replacing mod_func.c
 -> Compiling x86_64/core/mod2c/_mod_func.cpp
 -> Compiling x86_64/core/mod2c/_dimplic.cpp
 -> Compiling x86_64/core/mod2c/gap.cpp
x86_64/core/mod2c/gap.cpp(32): warning #47: incompatible redefinition of macro "_STRIDE" (declared at line 16 of "/p/project/cjzam11/kitayama1/opt/nrn-master/include/coreneuron/mechanism/mech/mod2c_core_thread.hpp")
  #define _STRIDE 1
          ^

x86_64/core/mod2c/gap.cpp(228): error: identifier "_vec_v" is undefined
      _v = _vec_v[_nd_idx];
           ^

x86_64/core/mod2c/gap.cpp(228): error: identifier "_nd_idx" is undefined
      _v = _vec_v[_nd_idx];
                  ^

x86_64/core/mod2c/gap.cpp(229): error: identifier "_PRCELLSTATE_V" is undefined
      _PRCELLSTATE_V
      ^

x86_64/core/mod2c/gap.cpp(235): error: identifier "_nt_data" is undefined
     i = ( v - vgap ) / r ;
               ^

x86_64/core/mod2c/gap.cpp(251): error: identifier "_vec_v" is undefined
      _v = _vec_v[_nd_idx];
           ^

x86_64/core/mod2c/gap.cpp(251): error: identifier "_nd_idx" is undefined
      _v = _vec_v[_nd_idx];
                  ^

x86_64/core/mod2c/gap.cpp(252): error: identifier "_PRCELLSTATE_V" is undefined
      _PRCELLSTATE_V
      ^

x86_64/core/mod2c/gap.cpp(253): error: initialization with "{...}" expected for aggregate object
   _g = _nrn_current(_v + .001);
        ^

x86_64/core/mod2c/gap.cpp(257): error: identifier "_nt_data" is undefined
   _g *=  1.e2/(_nd_area);
                ^

compilation aborted for x86_64/core/mod2c/gap.cpp (code 2)
make: *** [x86_64/core/build/gap.o] Error 2
```

**Comment by nrnhines** [comment]
I would strongly encourage the replacement of the gap.mod file that is using POINTER with a gap.mod file that makes use of ParallelContext transfer methods. The latter is thread safe and transfers can be interprocessor.

**Comment by ikitayama** [comment]
Would you mind pointing me in the right direction with an example?

**Comment by nrnhines** [comment]
The transfer methods are
https://www.neuron.yale.edu/neuron/static/py_doc/modelspec/programmatic/network/parcon.html#ParallelContext.setup_transfer
https://www.neuron.yale.edu/neuron/static/py_doc/modelspec/programmatic/network/parcon.html#ParallelContext.source_var
https://www.neuron.yale.edu/neuron/static/py_doc/modelspec/programmatic/network/parcon.html#ParallelContext.target_var
A modeldb example is
https://senselab.med.yale.edu/modeldb/ShowModel?model=45539 and see mod/par_ggap.mod and hoc/parlib2.hoc in particular the ```par_gap_create``` function.
An example in python is
https://github.com/nrnhines/ringtest.git and see mod/halfgap.mod and the mk_gap function in ring.py

**Comment by ikitayama** [comment]
Thank you, @nrnhines for a link to the model page. I'll take a look at it.

**Comment by ikitayama** [comment]
> Thank you, @nrnhines for a link to the model page. I'll take a look at it.

I think I was able to execute this on JURECA at JSC:

```./x86_64/special -python ringtest.py -tstop 10 -coredat coreneuron_data```

I will adjust locally developed .mod files to this scheme. Thanks!
