### ISSUE TITLE
nrnivmol_core for coreneuron (nrnivmodl equivalent)

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#38]
All NEURON users are familiar with building special using `nrnivmodl`.
When we build neuron, `nrnivmodl` script is generate which takes care of:
* fining all mod files and translating via nocmodl
* create shared / static library
* link with necessary neuron library and create `special`

Similar workflow should be available with CoreNEURON. We should create `nrnivmodl_core` as part of CMake installation.

@fouriaux : when you install neuron, check nrnivmodl script under `bin`. We have to use [configure_file](https://cmake.org/cmake/help/v3.2/command/configure_file.html) functionality of CMake.

**Comment by fouriaux** [comment]
current step done is to include mod2c as submodule of Coreneuron.
Next steps on this task are to actually generate nrnivmodl_core executable.

**Comment by fouriaux** [comment]
![neuron_flow](https://user-images.githubusercontent.com/28300081/31332732-d57107fc-ace7-11e7-8950-c1560e23548d.png)
![current_coreneuron_flow](https://user-images.githubusercontent.com/28300081/31332743-de761ebe-ace7-11e7-85d8-b360986fa794.png)

**Comment by fouriaux** [comment]
### Targetted merged NEURON and CORENEURON workflows
![coreneuron_flow_v5_aiming_final](https://user-images.githubusercontent.com/28300081/31332816-2209ecd2-ace8-11e7-9b00-31f858d41697.png)

**Comment by fouriaux** [comment]
### wrok flow in progress with pull request https://github.com/BlueBrain/CoreNeuron/pull/42
![coreneuron_flow_v2](https://user-images.githubusercontent.com/28300081/31332908-6d6a85ec-ace8-11e7-9649-535d15e1fb7d.png)
