### ISSUE TITLE
IClamp report

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/CoreNeuron#391]
The calculation of LFP apart from the `i_membrane` values also needs reporting on `IClamp`.
This is something not currently possible inside `CoreNEURON` and should be implemented to be able to calculate LFP post-sim by summing the values of `i_membrane` and `IClamp`, as discussed with Sirio.

**Comment by nrnhines** [comment]
Are you sure about this? With neurondemo and selecting the Patch:HH demo, setting ```cvode.use_fast_imem(1)``` and popping up a ```NEURONMainMenu/Graph/CurrentAxis``` and plotting ```soma.i_membrane_(.5)```, I see a membrane current which is the same as IClamp[0].i .  Are these not the same trajectories as with CoreNEURON?

**Comment by olupton** [comment]
This was resolved in https://github.com/BlueBrain/CoreNeuron/pull/514.
