### ISSUE TITLE
nrnbbcore_register_mapping doesn't work for artificial cells because somatic not a public member

### ISSUE THREAD

**Issue by WeinaJi** [BlueBrain/CoreNeuron#393]
As a work around for the error during the coreneuron data generation when no. of cells < no. of processes, I assign a fake gid to the artificial cell ```CoreConfig ``` and add it in the cell_distributor in neurodamus. And then I call ```nrnbbocore_register_mapping``` via ```Nd.registerMapping(cell_distributor)```, the error returned is
```
somatic not a public member of CoreConfig
4 skylake/x86_64/special: CoreConfig somatic
```

**Comment by pramodk** [comment]
This is Neurodamus specific issue. So we should close it here and create one on JIRA for Neurodamus project.

**Comment by olupton** [comment]
Moved to Neurodamus (BBPBGLIB-752).
