### ISSUE TITLE
CMake option to enable/disable legacy units

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#405]
NEURON is changing units values (CODATA 2018 constants), see : https://github.com/BlueBrain/mod2c/pull/47
As discussed in https://github.com/BlueBrain/mod2c/pull/47#issuecomment-711156915, we need to add `-DCORENEURON_ENABLE_LEGACY_UNIT=ON` option to CMake to enable/disable use of legacy units.

What needs to be done:
- [ ] add CMake switch CORENEURON_ENABLE_LEGACY_UNIT
- [x] `share/nrnunits.lib` in MOD2C should become template file `share/nrnunits.lib.in`
- [x] Depending on value of `CORENEURON_ENABLE_LEGACY_UNIT` option and using CMake's [configure_file](https://cmake.org/cmake/help/latest/command/configure_file.html) functionality, `share/nrnunits.lib.in` should be converted to `share/nrnunits.lib` at build time with old or new values of different constants. 

The same mechanism was used in earlier NEURON versions  (see usage of `NRN_ENABLE_LEGACY_FR` in [cmake/ConfigFileSetting.cmake](https://github.com/neuronsimulator/nrn/blob/6aff783a9e8c031a6071f7b917dca753ba7cfc19/cmake/ConfigFileSetting.cmake#L108)).

@iomaganaris  can provide additional context.

**Comment by alkino** [comment]
Why is this ticket in CoreNeuron and not in mod2c?
What about nmodl?

**Comment by iomaganaris** [comment]
`mod2c` has its `nrnunits.lib` in https://github.com/BlueBrain/mod2c/blob/master/share/nrnunits.lib and `NMODL` in https://github.com/BlueBrain/nmodl/blob/master/share/nrnunits.lib. They should both be edited to be able to select the legacy or new units.

**Comment by nrnhines** [comment]
the coreneuron eion.c file also uses this option.

**Comment by alkino** [comment]
Should I copy the file from neuronsimulator/nrn? They differ about available values sometimes.

**Comment by nrnhines** [comment]
You need to copy ```nrn/share/lib/nrnunits.lib.in``` . That uses ```@LegacyY@``` and ```@LegacyN@``` that get configured into 
```#``` and ```<empty>``` or vice versa depending on ```CORENRN_ENABLE_LEGACY_UNITS``` to create the ```nrnunits.lib``` file.

**Comment by alkino** [comment]
Waiting for BlueBrain/nmodl#411 and BlueBrain/mod2c#52

**Comment by nrnhines** [comment]
It may help to see how I changed mod2c parse1.y, nmodlfunc.h and units.c with regard to ```nrnunit_dynamic_str``` (which should probably be called nrnunit_format_str). Modern units have full double precision, legacy were ```%g```.
