### ISSUE TITLE
Remove use of CMake's ExternalProject to build MOD2C

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#406]
Currently we are using [ExternalProject ](https://cmake.org/cmake/help/latest/module/ExternalProject.html) to build mod2c in CoreNEURON : https://github.com/BlueBrain/CoreNeuron/blob/84d9f733ea57a81d26e22dbfdc9cd08ac4d83830/CMake/AddMod2cSubmodule.cmake#L37
This rebuilds MOD2C as separate project first and then builds CoreNEURON.

In order uniform CoreNEURON build and implement features like https://github.com/BlueBrain/CoreNeuron/issues/405, we should add mod2c as subdirectory into CoreNEURON project (I meant `add_subdirectory`) and build that as target of single CoreNEURON project. 

What needs to be done:

* Remove use of ExternalProject_Add and use add_subdirectory
* In mod2c, we could avoid building test target. See how do the same in CoreNEURON : https://github.com/BlueBrain/CoreNeuron/blob/84d9f733ea57a81d26e22dbfdc9cd08ac4d83830/CMakeLists.txt#L31

**Comment by alkino** [comment]
Fixed by #409
