### ISSUE TITLE
tarvis build integration

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#41]
Even though we have jenkin configuration with bbp cluster, it would be useful to add travis CI integration for Ubuntu and OS X platform to start with.

* Use NMODL project [travis configuration](https://github.com/BlueBrain/nmodl/blob/master/.travis.yml) as template
* Build for Ubuntu and OSX Platform

**Comment by tapaswenipathak** [comment]
Hi @pramodk, Can I work on this? I just found the project interesting and feel like this could be a nice ticket in knowing the project.

**Comment by pramodk** [comment]
Sure! [tests/jenkins/install.sh](https://github.com/BlueBrain/CoreNeuron/blob/master/tests/jenkins/install.sh) summarise the build options.

If you have any questions, please let us know.

**Comment by tapaswenipathak** [comment]
I was adding Travis CI, the `install.sh` file needs `modules.sh`. Can you please add this in the repository?

**Comment by tapaswenipathak** [comment]
Can you please let me know the -
- C++ version
- If you only like Travis enabled on Trusty? Xenial, Cosmos are available on Travis as well.
- macOS version? [versions information](https://docs.travis-ci.com/user/reference/osx/#macos-version).

**Comment by tapaswenipathak** [comment]
Can you please let me know the -
- C++ version
- If you only like Travis enabled on Trusty?
- [OS X version](https://docs.travis-ci.com/user/reference/osx/#macos-version)

**Comment by pramodk** [comment]
@tapaswenipathak : the `modules.sh` is specific to the cluster that we have. It just loaded necessary compilers.

What we need is to install necessary dependencies (cmake, flex, bison, mpi etc.) and then do cmake build.

* To see build dependencies installation, this [dockerfile](https://github.com/pramodk/neuron-icei/blob/master/Dockerfile) might give you an idea.
* To build you can just use similar to this [cmake options](https://github.com/pramodk/neuron-icei/blob/0d09ae88098d8ef270f533f29040e1edcb31c1a0/manual/installer.sh#L68). (ignore `-DADDITIONAL_MECHPATH`)

>C++ version

any c++11 supported (gcc 4.9>=) is fine

> If you only like Travis enabled on Trusty?

should be sufficient

> OS X version

10.14
