### ISSUE TITLE
Add the ability to select NEURON branch for jenkins CI

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/CoreNeuron#415]
This ticket is about selecting a specific `NEURON` branch in the Jenkins Pipeline CI of `CoreNEURON` based on the PR description.
Something similar is done in the `SimulationStack` CI here: https://bbpcode.epfl.ch/code/#/c/51178/
The file that configures Jenkins CI and needs changes is: https://github.com/BlueBrain/CoreNeuron/blob/master/tests/jenkins/Jenkinsfile

**Comment by olupton** [comment]
I think this was done by https://github.com/BlueBrain/CoreNeuron/pull/539/commits/c8809367e759a2ebc2eb1edff20ea7ef426bd2f7, but in any case the Jenkins CI should be decommissioned soon.
