### ISSUE TITLE
Caliper Instrumentor Profiling has no profiling output

### ISSUE THREAD

**Issue by HolyLow** [BlueBrain/CoreNeuron#449]
**Describe the issue**
I want to profile the coreneuron performance with MPI and GPU backend. 
As the caliper tool is provided as a instrumentor, I would like to enable caliper profiling.
However, after enabling caliper and running the program, there is no profiled output, neither in stdout nor in log file.

**To Reproduce**
```bash
# first of all, install the caliper library and setup corresponding enviroments.
# then we do the compilation.
$ mkdir -p test/coreneuron_profile_gpu && cd test/coreneuron_profile_gpu
$ cmake ../../CoreNeuron -DDADDITIONAL_MECHPATH=../../ringtest/mod -DCMAKE_C_FLAGS:STRING="-O2 -ta=tesla:cuda11.0 -lrt -D__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1 -L/home/username/install/caliper/lib" -DCMAKE_CXX_FLAGS:STRING="-O2 -ta=tesla:cuda11.0 -lrt -D__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1 -L/home/username/install/caliper/lib" -DCOMPILE_LIBRARY_TYPE=STATIC -DCUDA_HOST_COMPILER=`which gcc` -DCUDA_PROPAGATE_HOST_FLAGS=OFF -DENABLE_SELECTIVE_GPU_PROFILING=ON -DENABLE_OPENACC=ON -DNRN_ENABLE_GPU=ON -DCORENRN_ENABLE_GPU=ON -DCMAKE_INSTALL_PREFIX=../gpu_install -DCORENRN_ENABLE_CALIPER_PROFILING=ON
$ make -j
$ make install
$ cd ..
$ mpiexec -np 1 ./gpu_install/bin/nrniv-core --tstop 1000 --datpath ../ringtest/networks/10000Sim/core-1 --mpi --gpu
```

**Expected behavior**
I expect that the profiling log is printed on stdout or stored in some log file. 
But I've got nothing other than normal outputs where profiling is not enabled.
And when I read the sourcecode in CoreNeuron/coreneuron/utils/profile/profile_interface.h, I fail to see where the caliper implements its output utils.

**System (please complete the following information)**
 - OS: Ubuntu 20.04
 - Compiler: PGI 20.9
 - Version: master branch
 - Backend: CPU, GPU
 - caliper version: 2.5.0 (latest when this issue is posted on 30/12/2020)

**Comment by pramodk** [comment]
@HolyLow : were you able to get necessary profiling output?

**Comment by HolyLow** [comment]
Yeah, I studied the documents of caliper project, and found that there is a convenient way to enable the profiling, by setting environment variables CALI_CONFIG=runtime-report,calc.inclusive.
In this way, to get the profiling result, the run command can be:
```
CALI_CONFIG=runtime-report,calc.inclusive mpiexec -np 1 ./gpu_install/bin/nrniv-core --tstop 1000 --datpath ../ringtest/networks/10000Sim/core-1 --mpi --gpu
```
The method worked for me, at least so far... I think maybe some annotations in the source code or documentation will be handy for someone new to the profiling tools.

Thanks for your concern!

**Comment by pramodk** [comment]
> In this way, to get the profiling result, the run command can be:

👍 By the way, I created  #450 to make building easier. Now everything should work with:

```
cmake .. -DCORENRN_ENABLE_CALIPER_PROFILING=TRUE -Dcaliper_DIR=/path-to/caliper-2.0.1/share/cmake/caliper
```

Also there was a bug in the link order because of which mpi-runtime-report was not working correctly.

(here is the question that I posted last year https://github.com/LLNL/Caliper/issues/151 which has some config options).
