### ISSUE TITLE
Error : x86_64/corenrn/mod2c/cal.mod is not thread safe and incompatible with CoreNEURON

### ISSUE THREAD

**Issue by ikitayama** [BlueBrain/CoreNeuron#485]
**Describe the issue**
The model files can not be handled by `nrnivmodl -coreneuron`

**Expected behavior**
Successfully finish.

```
[...]
Mod files: "./cal.mod" "./kcRT03.mod" "./kdr.mod" "./matrix.mod" "./nafPR.mod" "./passiv.mod" "./rcadecay.mod" "./rkq.mod" "./vecst.mod"

Creating x86_64 directory for .o files.

COBJS=''
[INFO] Running: make -j4 -f /p/project/cjzam11/kitayama1/opt/nrn-master/share/coreneuron/nrnivmodl_core_makefile ROOT=/p/project/cjzam11/kitayama1/opt/nrn-master MODS_PATH=x86_64/corenrn/mod2c BUILD_TYPE=SHARED
NEURON { SUFFIX cal }
NEURON { SUFFIX cal }
NEURON { USEION ca WRITE ica }
NEURON { SUFFIX cal }
NEURON { USEION ca WRITE ica }
NEURON { SUFFIX cal }
NEURON { USEION ca WRITE ica }
Default NMODL flags:
Translating x86_64/corenrn/mod2c/cal.mod into x86_64/corenrn/mod2c//cal.cpp
INCLUDEing x86_64/corenrn/mod2c/geneval_cvode.inc
Translating x86_64/corenrn/mod2c/exp2syn.mod into x86_64/corenrn/mod2c//exp2syn.cpp
Notice: Assignment to the GLOBAL variable, "Inf", is not thread safe
Notice: Assignment to the GLOBAL variable, "Tau", is not thread safe
cvode_emit=0 cvode_not_allowed=0
Error : x86_64/corenrn/mod2c/cal.mod is not thread safe and incompatible with CoreNEURON
See details at https://neuron.yale.edu/neuron/docs/multithread-parallelizationTranslating x86_64/corenrn/mod2c/expsyn.mod into x86_64/corenrn/mod2c//expsyn.cpp
cvode_emit=0 cvode_not_allowed=0
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
make: *** [/p/project/cjzam11/kitayama1/opt/nrn-master/share/coreneuron/nrnivmodl_core_makefile:225: x86_64/corenrn/mod2c/cal.cpp] Aborted (core dumped)
make: *** Deleting file 'x86_64/corenrn/mod2c/cal.cpp'
make: *** Waiting for unfinished jobs....
diff: x86_64/corenrn/mod2c/_mod_func.cpp: No such file or directory
Translating x86_64/corenrn/mod2c/hh.mod into x86_64/corenrn/mod2c//hh.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/kcRT03.mod into x86_64/corenrn/mod2c//kcRT03.cpp
Notice: Assignment to the GLOBAL variable, "alpha", is not thread safe
Notice: Assignment to the GLOBAL variable, "beta", is not thread safe
cvode_emit=0 cvode_not_allowed=0
Error : x86_64/corenrn/mod2c/kcRT03.mod is not thread safe and incompatible with CoreNEURON
See details at https://neuron.yale.edu/neuron/docs/multithread-parallelizationThread Safe
make: *** [/p/project/cjzam11/kitayama1/opt/nrn-master/share/coreneuron/nrnivmodl_core_makefile:225: x86_64/corenrn/mod2c/kcRT03.cpp] Aborted (core dumped)
make: *** Deleting file 'x86_64/corenrn/mod2c/kcRT03.cpp'
```

The model files are checked out via:

`git clone https://github.com/ModelDBRepository/35358`

**Comment by ikitayama** [comment]
Is it still the user's job to appropriately change .mod files? It seems that even built-in mechanisms are affected too.

**Comment by nrnhines** [comment]
It is often the case with old mod files that ran on a a single thread, that GLOBAL variables were used to store temporary instance values to be used later. E.g In a DERIVATIVE block a rates function would be called to set several inf and tau gating rates and then those gating rates would be used in the following ode statements. This is an obvious race condition for multiple threads and thus not threadsafe. If suffices to declare the GLOBAL variables, used in that way, RANGE variables so there are separate  memory locations for every instance of them.  For other thread issues, the script ```mkthreadsafe`` can help. However, its solution to the above issue is to add the ```THREADSAFE``` keyword to the beginning of the NEURON block in the mod file which promotes the offending GLOBAL variables to thread instance variables. This is not sufficient for CoreNEURON GPU use. It is necessary for them to be RANGE variables.

**Comment by ikitayama** [comment]
@nrnhines what's the negative effect of changing automatically all those GLOBAL variables to RANGE ones? I've taken a quick look at the translated and created C code, cal.c, but I am not sure if I understand the difference immediately from the code.
I suppose threading support in NEURON has been around for some time, so I don't understand why there are so many thread-unsafe mod files.

**Comment by pramodk** [comment]
> @nrnhines what's the negative effect of changing automatically all those GLOBAL variables to RANGE ones?

GLOBAL variable has only one copy whereas RANGE variable is allocated one copy **per instance** (and hence more memory usage). 

But, you are right that some of this can be automatically done. This is what we are precisely doing in [new NMODL translator ](https://github.com/BlueBrain/nmodl) but this is not yet ready to be used by end users.

So for now, I would suggest to change GLOBAL variables manually. If you need any help / need clarification in the mod file, let us know.
