### ISSUE TITLE
coreneuron_modtests::fornetcon_py test fails on GPU

### ISSUE THREAD

**Issue by olupton** [BlueBrain/CoreNeuron#512]
**Describe the issue**
The `coreneuron_modtests::fornetcon_py` CTest test in NEURON fails when a GPU-enabled CoreNEURON build is used. Note that, because of this issue, the test is disabled by default and to see the problem you will have to re-enable it (remove `CONFLICTS gpu` in NEURON's `test/CMakeLists.txt`)

**To Reproduce**
Build NEURON against CoreNEURON with GPU support enabled, run
```bash
ctest -R coreneuron_modtests::fornetcon_py
```
from the build directory.

**Expected behavior**
Success.

**Logs**
When run normally, the error is
```
call to cuStreamSynchronize returned error 700: Illegal address during kernel execution
```
or in `cuda-gdb`:
```
CUDA Exception: Warp Illegal Address
The exception was triggered at PC 0x24b3580
Thread 1 "special-core" received signal CUDA_EXCEPTION_14, Warp Illegal Address.
[Switching focus to CUDA kernel 0, grid 31, block (0,0,0), thread (0,0,0), device 0, sm 0, warp 2, lane 0]
0x00000000024b35c0 in coreneuron::_net_buf_receive_ForNetConTest_310_gpu(coreneuron::NrnThread*)<<<(1,1,1),(128,1,1)>>> ()
```

**System (please complete the following information)**
 - OS: BB5
 - Compiler: NVHPC 21.2
 - Version: master
 - Backend: GPU

**Additional context**
Identified in the context of https://github.com/neuronsimulator/nrn/pull/1122.

cc: @pramodk @iomaganaris

**Comment by olupton** [comment]
Could this be related to https://github.com/BlueBrain/CoreNeuron/issues/347? I have not investigated further.

**Comment by pramodk** [comment]
Thats possible, need to look in details.

**Comment by olupton** [comment]
The problem seems to be that these members:
https://github.com/BlueBrain/CoreNeuron/blob/c1093ba9b327ec360068bc868c98ec1016cc6f0a/coreneuron/sim/multicore.hpp#L146-L148
are not copied to the GPU. I will look into how best to fix this...the use of `std::vector` here is a little awkward given how we handle this data transfer.
