### ISSUE TITLE
segmentation fault in bbcore_write when forgetting to setRNG in synapse

### ISSUE THREAD

**Issue by sharkovsky** [BlueBrain/CoreNeuron#52]
Currently, in a probabilistic synapse model, if I forget to call

```python
synapse.setRNG(int,int)
```
then, on a call to `pc.bbcore_write('coredat')` I get a Segmentation fault.
This was traced back to the fact that the random stream is set to `NULL`. 

It would be nicer if `bbcore_write` could check and output a a reminder to the user that they should set the Random123 generator with `setRNG` or equivalent call.

Thanks!

**Comment by nrnhines** [comment]
That sounds like a bug in the mod file implementation of bbcore_write of that synapse.
pc.bbcore_write would allow some synapses to use and some to not use random streams.
Eg. netstim.mod is a case in point.  If the Random123 generator is not set, and it absolutely has to be
then there should be a hoc_execerror in that synapses bbcore_write function.
