### ISSUE TITLE
Include NMODL in GitLab CI pipeline.

### ISSUE THREAD

**Issue by olupton** [BlueBrain/CoreNeuron#522]
Right now the GitLab CI pipeline that runs on BlueBrain hardware does not include [NMODL](https://github.com/BlueBrain/nmodl), only the legacy mod2c translator. We want to make NMODL the default soon, so we should be testing it.

**Describe the solution you'd like**
The GitLab CI pipeline, which already includes:
- CPU backend, Intel compiler
- GPU backend, NVHPC compiler

with mod2c translation, should be modified to add NMODL versions.

**Additional context**
- We should clone the CoreNEURON+NEURON build steps and add the `+nmodl` variant to CoreNEURON. Then there is a choice:
  - If we do nothing else then Spack will build NMODL as a dependency inside the CoreNEURON build jobs. We might need to tell Spack to build a `@develop` version of NMODL, and by default this will build NMODL with both NVHPC and Intel compilers.
  - Add a separate build job for NMODL and make the CoreNEURON-with-NMODL build jobs depend on this. It would be relatively easy here to share a single build of NMODL between the CoreNEURON-with-NMODL builds for CPU and GPU.
- The `hpc/cvf` internal project includes an example of building CoreNEURON against NMODL using a separate build job for NMODL.

**Comment by pramodk** [comment]
@alkino  : as a first step, we can start building NEURON locally with CoreNEURON and NMODL enabled:

```
git clone git@github.com:neuronsimulator/nrn.git
cd nrn
mkdir build
cmake .. -DCMAKE_INSTALL_PREFIX=./install \
  -DNRN_ENABLE_CORENEURON=ON \
  -DCORENRN_ENABLE_GPU=OFF \
  -DNRN_ENABLE_TESTS=ON \
  -DNRN_ENABLE_INTERVIEWS=OFF \
  -DNRN_ENABLE_RX3D=OFF \
  -DCORENRN_ENABLE_NMODL=ON
make -j
make test
```

**Comment by alkino** [comment]
Failing tests
``` 1/15 Test #29: coreneuron_modtests::datareturn_py .............***Failed    1.01 sec
 2/15 Test #35: external_ringtest::coreneuron_mpi ..............***Failed    2.45 sec
 3/15 Test #36: external_ringtest::coreneuron_mpi_threads ......***Failed    2.22 sec
 4/15 Test #37: external_ringtest::compare_results .............***Failed    0.04 sec
 5/15 Test #39: testcorenrn_bbcore::coreneuron_cpu_online ......***Failed    2.66 sec
 6/15 Test #40: testcorenrn_bbcore::coreneuron_cpu_offline .....***Failed    1.12 sec
 7/15 Test #42: testcorenrn_bbcore::compare_results ............***Failed    0.04 sec
 8/15 Test #54: testcorenrn_gf::coreneuron_cpu_online ..........***Failed    0.29 sec
 9/15 Test #55: testcorenrn_gf::coreneuron_cpu_offline .........***Failed    0.53 sec
10/15 Test #57: testcorenrn_gf::compare_results ................***Failed    0.03 sec
11/15 Test #78: testcorenrn_vecevent::coreneuron_cpu_online ....***Failed    1.00 sec
12/15 Test #79: testcorenrn_vecevent::coreneuron_cpu_offline ...***Failed    0.54 sec
13/15 Test #81: testcorenrn_vecevent::compare_results ..........***Failed    0.03 sec
14/15 Test #82: testcorenrn_netstimdirect::direct ..............***Failed    1.99 sec
15/15 Test #83: testcorenrn_netstimdirect::compare_results .....***Failed    0.04 sec
```

**Comment by alkino** [comment]
With the last 3 patches inside nmodl no tests are failing!

- https://github.com/BlueBrain/nmodl/commit/cb3c0bfa8d176f53bdac94d6cb4c6c41a20b1055
- https://github.com/BlueBrain/nmodl/commit/641ee616f92e1d551bff1b7d341210527a065bba
- https://github.com/BlueBrain/nmodl/commit/dcaf303566bf4a183cf667e31a45a680c7a006fe

**Comment by alkino** [comment]
If we disable https://github.com/BlueBrain/nmodl/blob/master/src/codegen/codegen_compatibility_visitor.cpp#L39-L40 all tests pass.

The long term solution is to introduce the support for DESTRUCTOR: https://github.com/BlueBrain/nmodl/issues/584

Tests are:
```
cd nrn && mkdir BUILD && cd BUILD
cmake -DCMAKE_INSTALL_PREFIX=/ -DNRN_ENABLE_CORENEURON=ON -DNRN_ENABLE_INTERVIEWS=OFF -DNRN_ENABLE_RX3D=ON -DCORENRN_ENABLE_NMODL=ON -DCMAKE_INSTALL_PREFIX=$PWD/INSTALL -DNRN_ENABLE_BINARY_SPECIAL=ON -DNRN_ENABLE_MPI=ON ..
make -j8 all test
```

Inside `channel-benchmark`:
```
nrnivmodl lib/modlib
nrnivmodl-core lib/modlib
./x86_64/special $HOC_LIBRARY_PATH/init.hoc
sort out.dat > neuron.dat
./x86_64/special -c arg_coreneuron=1 $HOC_LIBRARY_PATH/init.hoc
sort out.dat > neuron_coreneuron_nmodl.dat
diff neuron.dat neuron_coreneuron_nmodl.dat
```

**Comment by olupton** [comment]
Closed by https://github.com/BlueBrain/CoreNeuron/pull/575 (NMODL + CPU) and https://github.com/BlueBrain/CoreNeuron/pull/583 (NMODL + GPU).
