### ISSUE TITLE
change mallinfo to mallinfo2

### ISSUE THREAD

**Issue by alkino** [BlueBrain/CoreNeuron#558]
`mallinfo` is now deprecated because it use a structure of `int` to represent address.
We should use `mallinfo2` instead that return structure of `size_t`.

See https://man7.org/linux/man-pages/man3/mallinfo.3.html

**Comment by pramodk** [comment]
In the past, I was thinking about malloc_info: https://linux.die.net/man/3/malloc_info
But go ahead if mallinfo2 is better / easy to replace with!
