### ISSUE TITLE
Is there a website hosting execution results of neuron_direct.py?

### ISSUE THREAD

**Issue by ikitayama** [BlueBrain/CoreNeuron#582]
I'd like to check whether the `CaDynamics_E2` model described in `tests/jenkins/mod/CaDynamics_E2.mod` file.
Is the concentration supposed to be increased linearly over time, or oscillate? Your help is appreciated.

**Comment by pramodk** [comment]
@ikitayama : sorry, that test is bit misleading! It is meant to be just for checking compilation & linking of external mod file by neuron+coreneuron. It's not checking any scientific aspects of the mod file.

**Comment by ikitayama** [comment]
Thanks for your reply!
