### ISSUE TITLE
nrnivmodl errors with NVHPC in system-wide installation

### ISSUE THREAD

**Issue by olupton** [BlueBrain/CoreNeuron#584]
**Describe the issue**
In https://github.com/BlueBrain/CoreNeuron/issues/580#issuecomment-869628071 we saw that the NVHPC compilers do not cope with being explicitly told about system include paths:
```
$ echo "#include <cstdlib>" > foo.cpp && nvc++ -I/usr/include -o foo foo.cpp
"[snipped]/gcc-9.3.0-45gzrp/include/c++/9.3.0/cstdlib", line 75: catastrophic error: cannot open source file "stdlib.h"
  #include_next <stdlib.h>
                          ^
1 catastrophic error detected in the compilation of "foo.cpp".
Compilation terminated.
```
This seems to be a [known](https://forums.developer.nvidia.com/t/bug-in-pgc-18-10/136108) issue:
> To fix, remove the `-I/usr/include` from your compile options.

If CoreNEURON is installed to a system prefix (i.e. `-DCMAKE_INSTALL_PREFIX=/usr`) then CoreNEURON adds an explicit `-I/usr/include` to the compiler arguments used inside `nrnivmodl`, causing similar errors when `nrnivmodl` is called.

**To Reproduce**
[Presumably] build NEURON with NVHPC and
```
cmake .. -DNRN_ENABLE_CORENEURON=ON -DCORENRN_ENABLE_GPU=ON -DCMAKE_INSTALL_PREFIX=/usr
cmake --build . --parallel
cmake --build . --target install
```
and run `/usr/bin/nrnivmodl`.

**Expected behavior**
This should work, or there should be an error message saying that shared/system installations like this are not supported.

A fix might replicate some linker-related logic [in this file](https://github.com/BlueBrain/CoreNeuron/blob/8b9213cdc2072d8d1bc8ef7ca5ff4504acfd89b3/CMake/MakefileBuildOptions.cmake).

**Comment by pramodk** [comment]
@alkino : IIRC, you were looking into this, right?

**Comment by alkino** [comment]
@olupton Can you try with last NVHPC? And tell us if this problem still occurs

**Comment by olupton** [comment]
IIRC last time I tried to reproduce this I couldn't -- let's just close it.
