### ISSUE TITLE
Channel-Benchmark: CoreNeuron+MOD2C (GPU execution) - Different Spikes compared to NRN & weird messages regarding random number generation

### ISSUE THREAD

**Issue by kotsaloscv** [BlueBrain/CoreNeuron#593]
To reproduce this issue:
**1.** Clone channel benchmark (from bbpgitlab) and checkout to `update_scripts` branch.
**2.** Run the install script.
**3.** Submit (sbatch) the `run_gpu.sh` script.
**4.** The spikes generated from NRN simulation (`NRN_GPU.spk`) are a bit different from the ones generated from CoreNeuron+MOD2C (`GPU_MOD2C.spk`). The spikes can be found in `benchmark/channels` folder.
**5.** Inspect the `GPU_MOD2C.log` (in `benchmark/channels folder`) for some weird messages regarding random numbers that are generated:
`
Failure! 1.000000 at time 0.114331: urand = -nan
Failure! 1.000000 at time 0.111089: urand = 2.84441e-304
psolve |                                                         | t: 0.00   ETA: 0h00m00s
Failure! 1.000000 at time 0.114534: urand = -61.9845
Failure! 1.000000 at time 0.134616: urand = 2.35799e-310
Failure! 1.000000 at time 0.123452: urand = -0.000112443
Failure! 1.000000 at time 0.112969: urand = 1.29568e-304
 || SYN_ID: 1.000000, release failure || Failure! 1.000000 at time 0.158528: urand = 2.35795e-310
 || SYN_ID: 1.000000, release failure || Failure! 1.000000 at time 0.154727: urand = 2.358e-310
Failure! 1.000000 at time 0.170536: urand = -0.000296501
Failure! 1.000000 at time 0.179273: urand = 2.35799e-310
Failure! 1.000000 at time 0.173388: urand = 1.78944e-309
Failure! 1.000000 at time 0.178487: urand = 2.35795e-310
Failure! 1.000000 at time 0.21024: urand = -0.000292664
Failure! 1.000000 at time 0.179791: urand = -0.000405227
 || SYN_ID: 1.000000, release failure ||  || SYN_ID: 1.000000, release failure || Failure! 1.000000 at time 0.198301: urand = 8.12061e-06
Failure! 1.000000 at time 0.191264: urand = 9.31414e-15
...
`

**Comment by olupton** [comment]
This should have been fixed with #590, I think. Can you try updating to include that?

**Comment by kotsaloscv** [comment]
> This should have been fixed with #590, I think. Can you try updating to include that?

You are right #590 fixes this issue (both spikes & weird messages). I will just update the submodule in NRN repo.
