### ISSUE TITLE
Create debug version with all the prints inside macros working

### ISSUE THREAD

**Issue by iomaganaris** [BlueBrain/CoreNeuron#597]
**Describe the issue**
CoreNEURON has in a lot of places macros which enabled debug prints in multiple places. Due to the fact that those printfs are not compiled and tested currently a lot of them are not usable now and generate compilation errors.
It would be useful to fix these issues and find a better way to enable them using a CMake option (e.g. `-DCORENRN_ENABLE_DEBUG_LOG=ON`.

**Comment by iomaganaris** [comment]
I am afraid that enabling all the prints under macros is going to generate a very verbose output, which might be something we don't want to have with a `Debug` build type that we normally do to disable vectorization and compare binary results in the CI or during debugging. While conceptually it makes sense, I think that in practice it won't be convenient and might be better to add a new CMake option just for enabling the extra logs.

**Comment by alkino** [comment]
what about `CHKPNTDEBUG`, `CORENRN_DEBUG_QUEUE`, `INTERLEAVE_DEBUG`
