### ISSUE TITLE
Dynamic MPI support

### ISSUE THREAD

**Issue by alexsavulescu** [BlueBrain/CoreNeuron#600]
In the context of NEURON wheel integration of CoreNEURON we need to implement dynamic MPI capabilities. 

Before diving into implementation details, a few ideas to bare in mind:

* would it be possible to capitalize on the `libnrnmpi` library?
* if yes, for the short term we can detect is CoreNEURON is a submodule and use `libnrnmpi`; on the longer term, we can then see about implementing dynamic MPI in CoreNEURON or maybe extract `libnrnmpi` in another repo ?

**Comment by nrnhines** [comment]
> would it be possible to capitalize on the libnrnmpi library?

I think the answer is yes. But it is not clear to me how independent the data part has to be when NEURON and CoreNEURON coexist in direct mode. In direct mode, I think NEURON can initialize MPI and CoreNEURON just use that instance. Ie. the 
```
MPI_Comm nrnmpi_comm;
```
Something to note is that a script, mkdynam.sh, transforms the nrnmpidec.h list of nrnmpi wrappers for the desired MPI functions
into the helper files, nrnmpi_dynam_wrappers.inc, nrnmpi_dynam.h, nrnmpi_dynam_cinc.  And nrnmpi_dynam.cpp is responsible
for dlopening the correct libmpi and then, based on the libmpi implementation, dlopening the correct libnrnmpi.

**Comment by pramodk** [comment]
@alexsavulescu : this ticket would require some analysis of current code usage in CoreNEURON. We can have discussion about this in next month / after summer break.

**Comment by pramodk** [comment]
Tagging here @sergiorg-hpc as well as he has recent experience with dynamic library loading. Next week can discuss some of the technical details.

**Comment by olupton** [comment]
I pushed a sketch of how I think this could be handled to https://bbpgitlab.epfl.ch/hpc/user/coreneuron-dynamic-mpi-sandbox (https://godbolt.org/z/erY4Y6f9K is a single-file no-dependency version of the same).

**Comment by olupton** [comment]
Some pointers/next steps:
- The `nrnmpi_...` functions that are used in the CoreNEURON code are declared [here](https://github.com/BlueBrain/CoreNeuron/blob/db8477c90fe33f6c7f7025482e81ac0972ed12d0/coreneuron/mpi/nrnmpidec.h) and defined [here](https://github.com/BlueBrain/CoreNeuron/blob/db8477c90fe33f6c7f7025482e81ac0972ed12d0/coreneuron/mpi/mpispike.cpp).
- In CoreNEURON these should be replaced with instances of the `mpi_function<...>` helper in the coreneuron-dynamic-mpi-sandbox example above. These should be callable exactly as before, i.e. no changes should be needed at the call sites: https://github.com/BlueBrain/CoreNeuron/blob/db8477c90fe33f6c7f7025482e81ac0972ed12d0/coreneuron/utils/memory_utils.cpp#L82-L84
- With dynamic MPI **disabled** in CoreNEURON (i.e. taking the 2nd branch of https://bbpgitlab.epfl.ch/hpc/user/coreneuron-dynamic-mpi-sandbox/-/blob/aab81a461c3a1d69ac4aaa760ee1eec04068ab23/include/coreneuron/mpi_utils.h#L49-58), nothing should break. Implementations like [this](https://github.com/BlueBrain/CoreNeuron/blob/db8477c90fe33f6c7f7025482e81ac0972ed12d0/coreneuron/mpi/mpispike.cpp#L485-L501) are compiled/linked into other CoreNEURON code, `-lmpi` is used.
- With dynamic MPI **enabled** in CoreNEURON, we need to compile a separate shared library containing the implementations like [this](https://github.com/BlueBrain/CoreNeuron/blob/db8477c90fe33f6c7f7025482e81ac0972ed12d0/coreneuron/mpi/mpispike.cpp#L485-L501). This shared library is linked with `-lmpi`, but CoreNEURON/special/... do not link against it. It should be dynamically loaded if `--mpi` is passed, the instances of `mpi_function<...>` will use it to initialise their function pointers to the implementations.

For this ticket, we can ignore the possibility of having multiple MPI implementations. Later, when CoreNEURON and NEURON are more tightly integrated, we can inherit that logic from NEURON.

cc: @pramodk @alexsavulescu @alkino
