### ISSUE TITLE
NRN_ENABLE_MPI=(ON|OFF) does not automatically adjust the CORENRN_ENABLE_MPI flag

### ISSUE THREAD

**Issue by kotsaloscv** [BlueBrain/CoreNeuron#628]
Should we propagate the `NRN_ENABLE_MPI=(ON|OFF)` to the coresponding option in CoreNEURON `CORENRN_ENABLE_MPI =(ON|OFF)` ?

Now the propagation is not happening, i.e. if `NRN_ENABLE_MPI=OFF` this does not force `CORENRN_ENABLE_MPI` to be `OFF` as well.

**Comment by pramodk** [comment]
Didn’t realise this was not taken care in NEURON cmake. One liner change needs to be done here: https://github.com/neuronsimulator/nrn/blob/bcf44f673d43cc9a43458897e4b8264f265fde65/CMakeLists.txt#L415

**Comment by alexsavulescu** [comment]
Fixed upstream.

**Comment by nrnhines** [comment]
I agree with the change. But somewhat pedantically, it was  possible to create a CoreNEURON file transfer mode model using serial NEURON and run  with mpi parallel CoreNEURON. Nevertheless, it's nice to not require mpi be turned off explicitly on the
CoreNEURON side when it is turned off explicitly on the NEURON side.

**Comment by pramodk** [comment]
> Nevertheless, it's nice to not require mpi be turned off explicitly on the CoreNEURON side when it is turned off explicitly on the NEURON side.

Yeah exactly. And it causes confusion about what are MPI ON/OFF requirements and which libraries are linked etc etc.

**Comment by alexsavulescu** [comment]
> I agree with the change. But somewhat pedantically, it was possible to create a CoreNEURON file transfer mode model using serial NEURON and run with mpi parallel CoreNEURON. Nevertheless, it's nice to not require mpi be turned off explicitly on the
> CoreNEURON side when it is turned off explicitly on the NEURON side.

The more synergy the better. To be revisited with implementing dynamic MPI support for CoreNEURON  #600
