### ISSUE TITLE
Update Jenkins plan to execute tests on GPU

### ISSUE THREAD

**Issue by pramodskumbhar** [BlueBrain/CoreNeuron#63]
To avoid issues like #61, Jenkins plan should execute tests on GPU as well.

Have to check how `make test` should handle these tests because they need external variables setup (CUDA_VISIBLE_DEVICES) on our cluster.

cc: @fouriaux

**Comment by iomaganaris** [comment]
The [Jenkins plan](https://github.com/BlueBrain/CoreNeuron/blob/master/tests/jenkins/Jenkinsfile) of `CoreNeuron` was extended accordingly to run tests on GPU as well.
