### ISSUE TITLE
[GPU] Issue while building mod files using vector_capacity(void* v) and vector_vec(void* v)

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/CoreNeuron#638]
**Describe the issue**

Recently some of the BBP mod files are updated to use `vector_capacity` and `vector_vec`:

```python

NET_RECEIVE (weight, weight_AMPA, weight_NMDA, Psurv, nc_type) {
    : Psurv - survival probability of unrecovered state
    : nc_type:
    :   0 = presynaptic netcon
    :   1 = spontmini netcon
    :   2 = replay netcon

    LOCAL result, ves, occu
    weight_AMPA = weight
    weight_NMDA = weight * NMDA_ratio

    INITIAL {
        if (nc_type == 0) {  :// presynaptic netcon
    VERBATIM
            // setup self events for delayed connections to change weights
            void *vv_delay_times = *((void**)(&_p_delay_times));
            void *vv_delay_weights = *((void**)(&_p_delay_weights));
            if (vv_delay_times && vector_capacity(vv_delay_times)>=1) {
                double* deltm_el = vector_vec(vv_delay_times);
                int delay_times_idx;
                next_delay = 0;
                for (delay_times_idx = 0; delay_times_idx < vector_capacity(vv_delay_times); ++delay_times_idx) {
                    double next_delay_t = deltm_el[delay_times_idx];
    ENDVERBATIM
                    net_send(next_delay_t, 1)
    VERBATIM
                }
            }
    ENDVERBATIM
        }
    }
```

While compiling these mod files with CoreNEURON+GPU, we get:

```console
NVC++-S-1061-Procedures called in a compute region must have acc routine information - coreneuron::vector_capacity(void *) (x86_64/corenrn/mod2c/DetGABAAB.cpp: 522)
NVC++-S-0155-Accelerator region ignored; see -Minfo messages  (x86_64/corenrn/mod2c/DetGABAAB.cpp: 512)
NVC++-S-1061-Procedures called in a compute region must have acc routine information - coreneuron::vector_capacity(void *) (x86_64/corenrn/mod2c/ProbAMPANMDA_EMS.cpp: 590)
NVC++-S-0155-Accelerator region ignored; see -Minfo messages  (x86_64/corenrn/mod2c/ProbAMPANMDA_EMS.cpp: 580)
````

**To Reproduce**

* Install coreneuron with GPU support 
* Compile any recent [synapse mod file](https://bbpcode.epfl.ch/browse/code/sim/models/common/tree/mod/ProbAMPANMDA_EMS.mod#n244) from BBP model (or any other mod file with call to vector_capacity and vector_vec).

**Expected behavior**

Mod files should compile fine with GPU enabled CoreNEURON. 

**System (please complete the following information)**
* BB5

**Additional context**

Note that those mod files have:

```cpp
#ifndef CORENEURON_BUILD
extern int ifarg(int iarg);

extern void* vector_arg(int iarg);
extern double* vector_vec(void* vv);
extern int vector_capacity(void* vv);
#endif
```

i.e. these functions were supposed to call from NEURON only. With the change for delayed connections, verbatim blocks now introduced these functions into CoreNEURON as well.

I am looking into annotation of above functions with OpenACC. But other question is, do we need to (or should we) use these functions on CoreNEURON side?

@ohm314 and @jamesgking can answer this?

**Comment by ohm314** [comment]
At least in the current implementation they are needed in coreneuron too. The reason is that `NET_RECEIVE` itself now has a verbatim block, which calls `vector_vec` and `vector_capacity`.

**Comment by ferdonline** [comment]
> The reason is that `NET_RECEIVE` itself now has a verbatim block, which calls `vector_vec` and `vector_capacity`.

And I don't think we can drop it, since we want to access a Hoc Vector (probably the only option to pass arrays from hoc/python to mod). Numpy C API is an option? (I guess not).
Either way, the problem is that these routines are not compiled with nvcc too?
