### ISSUE TITLE
Random123 does not cope with ABM feature macros with PGI/NVIDIA compilers.

### ISSUE THREAD

**Issue by olupton** [BlueBrain/CoreNeuron#724]
**Describe the issue**
The 21.11 versions of the NVIDIA HPC compilers detect ABM instruction support on more machines.
These compilers default to enabling all instructions detected on the compilation machine (`-tp host`).
For example, BB5 nodes support ABM so from 21.11 `__ABM__` is defined by default, which breaks Random123 compilation:
```
"include/Random123/features/sse.h", line 56: catastrophic error #1697: cannot open source file "intrin.h"
  #include <intrin.h>
                     ^
```

In https://github.com/BlueBrain/spack/pull/1392 we added `-mno-abm` to the Spack recipes for CoreNEURON and NEURON to allow NVHPC 21.11 to be deployed, but this is a suboptimal place to fix the issue.

We should report this to upstream and/or add workarounds to the CMake configuration of CoreNEURON and NEURON, as most people do not compile via our private fork of Spack.

**Additional context**
- NVIDIA forum post: https://forums.developer.nvidia.com/t/21-11-tp-behaviour/198115
- https://github.com/BlueBrain/CoreNeuron/wiki/NERSC-GPU-hackathon-(Dec-2021)/#building describes a similar issue that also affected older compilers, which detected ABM support on some AMD CPUs.

**Comment by aweaver1fandm** [comment]
I also got this error regarding intrin.h while building on an Ubuntu 20.04 system.  As a temporary fix I modified sse.h so that instead of using intrin.h it uses immintrin.h.  This is an untested workaround and certainly not meant to be a fix of any sort

**Comment by pramodk** [comment]
> In BlueBrain/spack#1392 we added -mno-abm to the Spack recipes for CoreNEURON and NEURON to allow NVHPC 21.11 to be deployed, but this is a suboptimal place to fix the issue.

@olupton: as a temporary workaround, something similar needs to be done in neuron CMake?

**Comment by olupton** [comment]
Yes
> and/or add workarounds to the CMake configuration of CoreNEURON and NEURON

was getting at that. I'll take a look at that today.
