### ISSUE TITLE
BEFORE and AFTER keywords don't compile in mod files

### ISSUE THREAD

**Issue by nrnhines** [BlueBrain/CoreNeuron#746]
The declaration of  ```extern void hoc_reg_ba(int, mod_f_t, int);``` is not known to mod2c translated mod files.
The simple fix is to add that to coreneuron/mechanism/membfunc.hpp . However on updating testcorenrn so that
```
hines@hines-T7500:~/neuron/before-after/external/tests/testcorenrn$ git diff
diff --git a/mod/Gfluct3.mod b/mod/Gfluct3.mod
index b808620..5abd637 100644
--- a/mod/Gfluct3.mod
+++ b/mod/Gfluct3.mod
@@ -232,8 +232,7 @@ VERBATIM
 ENDVERBATIM
 }
 
-:BEFORE BREAKPOINT {
-PROCEDURE foo() {
+BEFORE BREAKPOINT {
        if (on > 0) {
                g_e = g_e0 + g_e1
                if (g_e < 0) { g_e = 0 }
@@ -249,7 +248,6 @@ PROCEDURE foo() {
 
 
 BREAKPOINT {
-      foo()
       i = ival   
     }
```
I am observing with ``` ninja test```
```
The following tests FAILED:
	 67 - testcorenrn_gf::compare_results (Failed)
```
Note: I'm trying to update the HNN model (https://github.com/jonescompneurolab/hnn-core) to work with CoreNEURON and that uses
```
hines@hines-T7500:~/models/hnn/hnn_core/mod$ grep BEFORE *.mod
dipole_pp.mod:BEFORE INITIAL {
dipole_pp.mod:BEFORE BREAKPOINT {
hines@hines-T7500:~/models/hnn/hnn_core/mod$ grep AFTER *.mod
dipole.mod:AFTER SOLVE {
dipole.mod:AFTER INITIAL {
dipole_pp.mod:AFTER SOLVE {
dipole_pp.mod:AFTER INITIAL {
```

**Comment by nrnhines** [comment]
> ```67 - testcorenrn_gf::compare_results (Failed)```

False alarm. The outgf.dat spike rasters must not have been sorted with sortspike. Just need to fix up the test to do that.

**Comment by olupton** [comment]
They should be sorted inside the comparison script:
https://github.com/neuronsimulator/nrn/blob/33ea2b983338cca0f54f90cbd575dc6c4bd5e4c3/test/scripts/compare_test_results.py#L49-L61

but maybe something is missing in the logic.

**Comment by nrnhines** [comment]
My mistake. I only checked the output files manually. With ```ctest -VV -R testcorenrn_gf::compare_results``` I see,
```
67: neuron matches coreneuron_cpu_online
67: neuron matches coreneuron_cpu_online_psolve_alternate
67: neuron matches coreneuron_cpu_offline
67: neuron DOES NOT match reference_file
```
So I have to understand why the reference vs new results are different with respect to the change from doing a procedure call in the BREAKPOINT vs doing that procedure in a BEFORE BREAKPOINT block.

**Comment by nrnhines** [comment]
Ok. The reference was correct and the change to Gfluct.mod needed to deal properly with the CONDUCTANCE.
```
100% tests passed, 0 tests failed out of 105
```
Now comes the painful process of a pull request involving three repositories :)

**Comment by pramodk** [comment]
As BEFORE/AFTER is not supported in new NMODL, we might need to add conflict with nmodl for time being. I will look into implementing support for this feature.
