### ISSUE TITLE
NVC++ fails to compile SH_na8st.mod with OpenMP target offload.

### ISSUE THREAD

**Issue by olupton** [BlueBrain/CoreNeuron#767]
**Describe the issue**
Now https://github.com/BlueBrain/nmodl/pull/804 is merged, the OpenMP-annotated C++ generated by NMODL from [SH_na8st.mod](https://github.com/pramodk/reduced_dentate/blob/70f363d7f82dfe6037fbddd8ed2e58cb20df6343/mechanisms/SH_na8st.mod) does not compile with NVC++/22.1 with GPU offload enabled. See, for example, https://bbpgitlab.epfl.ch/hpc/coreneuron/-/jobs/139498#L605:
```
NVC++-S-1073-Procedures called in a OpenMP target region must have 'omp declare target' information - Eigen::Matrix<double, T1, (int)1, (int)0, T1, (int)1> partialPivLu<(int)8>(const Eigen::Matrix<double, T1, ... (x86_64/corenrn/mod2c/SH_na8st.cpp: 77)
NVC++/x86-64 Linux 22.1-0: compilation completed with severe errors
make: *** [x86_64/corenrn/build/SH_na8st.o] Error 2
```
in principle these methods do have `omp declare target` directives:
https://github.com/BlueBrain/nmodl/blob/2833671832fd5f062439a7b633910fa499a5c428/src/solver/partial_piv_lu/partial_piv_lu.h#L26

**To Reproduce**
https://github.com/BlueBrain/CoreNeuron/pull/766 is running a clean version of the CI to demonstrate.

**Expected behaviour**
This should work!

cc: @iomaganaris @alkino @cattabiani

**Comment by olupton** [comment]
Some observations:

I tried bypassing the CUDA wrapper function `partialPivLu` by changing the condition [here](https://github.com/BlueBrain/nmodl/blob/2833671832fd5f062439a7b633910fa499a5c428/src/solver/newton/newton.hpp#L76), which gives me a different error:
```
NVC++-S-0000-Internal compiler error. accel.c::acc_remove_atomics: ILI_ALT is missing for atomicrmw opcode     402  (SH_na8st.cpp: 402)
NVC++/x86-64 Linux 22.1-0: compilation completed with severe errors
```

When I also tried preprocessing the source first, removing the implicit includes from the beginning
```bash
last_preinclude_line=$(grep -n '_preinclude.h"' "${preproc_source}" | tail -n 1 | cut -d : -f 1)
sed "1,${last_preinclude_line}d" "${preproc_source}" > stripped_${preproc_source}
```
and then compiling it, then I also saw
```
NVC++-F-1196-OpenMP - Standalone 'omp parallel' in a 'declare target' routine is not supported yet.  (stripped_tmp.cpp: 152)
```
which might be a clue (or a red herring), and seems related to https://github.com/BlueBrain/eigen/blob/0cfcbc88fb232f2bdea6038ce5a242454e950acb/Eigen/src/Core/products/Parallelizer.h#L151. I only see this if  I remove `-Mautoinline`, which [is passed by default](https://github.com/BlueBrain/CoreNeuron/blob/cbc70375c862a05d112237a966e9a74e588abde1/CMake/OpenAccHelper.cmake#L83).

**Comment by cattabiani** [comment]
I really suggest you to wait for @iomaganaris to comment on this. He did a lot of work for making eigen work in some way with gpu
