### ISSUE TITLE
Asking for help with error: nrniv: CoreNEURON cannot simulate a model that contains the extracellular mechanism

### ISSUE THREAD

**Issue by aweaver1fandm** [BlueBrain/CoreNeuron#769]
**Describe the issue**
I am trying to adapt a researcher's code to use CoreNeuron and when I run it I get the following error:

nrniv: CoreNEURON cannot simulate a model that contains the extracellular mechanism

I am just looking for some help/clarification on what I might be missing in converting the code over.  I couldn't seem to find much on line regarding the error

**To Reproduce**
I compile the mod files as:
nrnivmodl -coreneuron ./

and then run the simulation as
nrniv beginSimulation.hoc

This eventually calls the .hoc file I have attached here.  It is in this file I made the modifcations to use coreneuron as this is where in the original simulation run() was actually called, specifically the function func_evaluateFRandCV().  The modifcations I made are

/* Disabling regular Neuron and enabling Core Neuron -- TW */

    /* Running simulation. init() is automatically invoked */
    // run()

    /* Enable efficient cache -- TW */
    cvode.use_fast_imem(1)
    cvode.cache_efficient(1)

    /* Enable CoreNeuron and start the run -- TW */
    if (!nrnpython("from neuron import coreneuron")) {
        printf("*** ERROR: Python not available ***\n")
        return
    }

    po = new PythonObject()
    po.coreneuron.enable = 1
    pc = new ParallelContext()
    pc.set_maxstep(10)
    stdinit()
    pc.psolve(tstop)
 
and then the code continues as it was originally written

  /* Invoking function to calculate the firingRate */
    meanFiringRate = func_calculateFiringRate($1,$2,0) // (1: startTime, 2: stopTime, 3: printingFlag)

    /* Calculating conductionDistance */
    if (proximalLocationFlag==0) {
        pyramidalCell.iseg { distance() }
    } else {
        pyramidalCell.nodes[proximalLocation] { distance() }
    }
    pyramidalCell.nodes[distalLocation] { conductionDistance = distance(0.5) }

    /* Printing case-based outcome */
.....
[auxiliaryProcedures.txt](https://github.com/BlueBrain/CoreNeuron/files/7981872/auxiliaryProcedures.txt)

**Comment by nrnhines** [comment]
The model can run with CoreNEURON only if extracellular is being used only to calculate ```i_membrane```. In that case you can remove the ```insert extracellular``` statements and accomplish the same thing with ```cvode.use_fast_imem(1)``` (as you indicated above).  I don't see any mention of extracellular in your auxiliaryProcedures.txt file, so there must be other model files that mention it.

**Comment by aweaver1fandm** [comment]
Thank you. That is very helpful. I will look through the other parts of the
code to correct the problem. You can close this issue

**Comment by alexsavulescu** [comment]
For reference: https://nrn.readthedocs.io/en/latest/coreneuron/non_supported_features.html and https://nrn.readthedocs.io/en/latest/coreneuron/how-to/coreneuron.html
