### ISSUE TITLE
NEURON + direct mode CoreNEURON has MPI_Finalize problem

### ISSUE THREAD

**Issue by nrnhines** [BlueBrain/CoreNeuron#773]
**Describe the issue**
```ninja test``` from NEURON configured with ```-DNRN_ENABLE_CORENEURON=ON``` yields
```
38 - coreneuron_modtests::spikes_mpi_file_mode_py_cpu (Failed)
```

**To Reproduce**
Use current master of nrn. i.e. 8.0a-743-g3871f82a4
```
cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=install -DPYTHON_EXECUTABLE=`which python3` -DNRN_ENABLE_RX3D=OFF -DCMAKE_BUILD_TYPE=Debug  -DNRN_ENABLE_CORENEURON=ON -DNRN_ENABLE_TESTS=ON
ninja install
ctest -R spikes_mpi_file_mode_py_cpu -VV
```
generates
```
38: *** The MPI_Iprobe() function was called after MPI_FINALIZE was invoked.
38: *** This is disallowed by the MPI standard.
38: *** Your MPI job will now abort.
```

**Expected behavior**
As this has been working for quite a while, it is a surprise that it has started happening. If ```coreneuron.enable=False``` the problem goes away.

**System (please complete the following information)**
 - OS: [e.g. Ubuntu 18.04]
 - Compiler: [gcc 7.5]
 - Version: [master branch  3871f82a46b060a ]
 - Backend: [x86_64]

**Comment by nrnhines** [comment]
The problem may not be directly related to CoreNEURON and this issue perhaps should be moved over to the NEURON side.
It appears that the issue is due to the NEURON GUI being active (the gui is turned off when nrniv is launched with -mpi) in this test (python was launched and ```from neuron import h, gui``` This means the gui thread runs every 0.1s and calls ```void Oc::notify()``` which ```if (bbs_poll_ > 0) bbs_handle();``` which checks for a bulletin board message by calling ```MPI_Iprobe```.
I guess it was an oversight that the gui was not turned OFF by ```h.nrnmpi_init()```.  And it isn't clear why the bulletin board was active.

**Comment by nrnhines** [comment]
As expected the problem goes away if ```hoc_usegui = 0;``` is added to ```h.nrnmpi_init()```. Also the bulletin board becomes active when the first ParallelContext is created on rank 0. I suppose that could be deferred to when ```pc.runworker()``` is called but that's unnecessary here and needs some thought anyway.  It is not exactly clear how CoreNEURON got implicated in this but  I'm not curious enough to track that down.

**Comment by ramcdougal** [comment]
This isn't a bug in NEURON, this is a bug in the test code.

Importing `gui` explicitly enables the GUI. Scripts that don't intend to use the GUI should not import `gui`. There's an anti-pattern of enabling the GUI for side-effects of loading NEURON libraries. Just load the libraries that are desired instead.

**Comment by nrnhines** [comment]
From the beginning, it's been a vexing question of how to know if nrniv (or python) has been launched with the intention of running under MPI (e.g. mpiexec, mpirun, ...). I've always regretted the need for the ```-mpi``` arg. Anyway, I've always liked the ability to use the same code with and without mpi. At the same time, I've often wondered if there is a way to practically combine GUI + MPI. E.g. with GUI on only rank 0 and the bulletin board, optimization with the multirun fitter is already implemented. An enabling feature of the old PVM was that the virtual machine was assembled by the bulletin board after launch so one could request multiple processes from the multirun fitter itself. But generally, actually using a GUI with native MPI, seems like it would founder on the complexity of managing a multiprocess model. Hence the decision to turn it off when MPI was initialized.
I agree with
> There's an anti-pattern of enabling the GUI for side-effects of loading NEURON libraries

But I don't what that to be an error.
Perhaps ```h.nrnmpi_init()``` should turn off the GUI only if ```pc.nhost() > 1```.

I'll look for another way to avoid the MPI_Finalize problem.
