### ISSUE TITLE
Building NEURON+CoreNEURON with Caliper Profiling

### ISSUE THREAD

**Issue by Kim1230** [BlueBrain/CoreNeuron#849]
**Describe the issue**
I want to profile the ring-master package with caliper. 

**To Reproduce**
build caliper: `cmake ..  -DCMAKE_INSTALL_PREFIX=/home/yjy/CaliperInstall -DWITH_MPI=/opt/intel/oneapi/mpi `
build nrn: 
`cmake ..  -DNRN_ENABLE_CORENEURON=ON  -DNRN_ENABLE_INTERVIEWS=OFF -DNRN_ENABLE_RX3D=OFF  -DCMAKE_INSTALL_PREFIX=/home/yjy/nrn_CPU_Capiler -DNRN_ENABLE_PROFILING=ON -DNRN_PROFILER=caliper -DCMAKE_PREFIX_PATH=/home/yjy/CaliperInstall/share/cmake/caliper -DCMAKE_C_COMPILER=/opt/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/icc -DCMAKE_CXX_COMPILER=/opt/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/icpc`
test ring-master:
`
nrnivmodl -coreneuron mod
CALI_CONFIG=runtime-report,profile.mpi mpiexec.hydra -n 2 ./x86_64/special -mpi -python ringtest.py -tstop 100 -coreneuron
`

**Expected behavior**
I expect It will work and give the output of the execution steps.

**Logs**

 => LINKING executable ./special LDFLAGS are:    -pthread -lreadline -lcurses -lform  /home/y00648680/python3.8/lib/libpython3.8.so -Wl,-rpath,/home/y00648680/python3.8/lib /opt/intel/oneapi/mpi/2021.6.0/lib/libmpifort.so -Wl,-rpath,/opt/intel/oneapi/mpi/2021.6.0/lib /opt/intel/oneapi/mpi/2021.6.0/lib/release/libmpi.so                         -Wl,-rpath,/opt/intel/oneapi/mpi/2021.6.0/lib/release -ldl -lrt -lpthread

And 
./x86_64/special: error while loading shared libraries: libcaliper.so.2: cannot open shared object file: No such file or directory
./x86_64/special: error while loading shared libraries: libcaliper.so.2: cannot open shared object file: No such file or directory

**System (please complete the following information)**
 - OS: [Centos7]
 - Compiler: OneAPI icc and icpc
 - Version:8.2.0
 - Backend:CPU

The build reuslt shows:
- Configured CoreNEURON 8.2.0
--
-- You can now build CoreNEURON using:
--   cmake --build . --parallel 8 [--target TARGET]
-- You might want to adjust the number of parallel build jobs for your system.
-- Some non-default targets you might want to build:
-- --------------------+--------------------------------------------------------
--  Target             |   Description
-- --------------------+--------------------------------------------------------
-- install             | Will install CoreNEURON to: /home/yjy/nrn_CPU_Capiler
-- docs                | Build full docs. Calls targets: doxygen, sphinx
-- --------------------+--------------------------------------------------------
--  Build option       | Status
-- --------------------+--------------------------------------------------------
-- CXX COMPILER        | /opt/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/icpc
-- COMPILE FLAGS       | -fPIC -qopenmp  -Wno-unknown-pragmas -g  -O2  -std=c++14
-- Build Type          | SHARED
-- MPI                 | ON
--   DYNAMIC           | OFF
--   INC               | /opt/intel/oneapi/mpi/2021.6.0/include
-- OpenMP              | ON
-- Use legacy units    | OFF
-- NMODL               | OFF
-- MOD2CPP PATH        | /home/yjy/nrn/build/bin/mod2c_core
-- GPU Support         | OFF
-- Auto Timeout        | ON
-- Wrap exp()          | OFF
-- SplayTree Queue     | ON
-- NetReceive Buffer   | ON
-- Caliper             | ON
-- Likwid              | OFF
-- Unit Tests          | OFF
-- Reporting           | OFF
-- --------------+--------------------------------------------------------------
--  See documentation : https://github.com/BlueBrain/CoreNeuron/
-- --------------+--------------------------------------------------------------
--
-- Configured NEURON 8.2.0
--
-- You can now build NEURON using:
--   cmake --build . --parallel 8 [--target TARGET]
-- You might want to adjust the number of parallel build jobs for your system.
-- Some non-default targets you might want to build:
-- --------------+--------------------------------------------------------------
--  Target       |   Description
-- --------------+--------------------------------------------------------------
-- install       | Will install NEURON to: /home/yjy/nrn_CPU_Capiler
--               | Change the install location of NEURON using:
--               |   cmake <src_path> -DCMAKE_INSTALL_PREFIX=<install_path>
-- docs          | Build full docs. Calls targets: doxygen, notebooks, sphinx, notebooks-clean
-- uninstall     | Removes files installed by make install (todo)
-- --------------+--------------------------------------------------------------
--  Build option | Status
-- --------------+--------------------------------------------------------------
-- C COMPILER    | /opt/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/icc
-- CXX COMPILER  | /opt/intel/oneapi/compiler/2022.1.0/linux/bin/intel64/icpc
-- BUILD_TYPE    | RelWithDebInfo (allowed: Custom;Debug;Release;RelWithDebInfo;Fast)
-- COMPILE FLAGS | -g  -O2
-- Shared        | ON
-- Default units | modern units (2019 nist constants)
-- MPI           | ON
--   DYNAMIC     | OFF
--   INC         | /opt/intel/oneapi/mpi/2021.6.0/include
--   LIB         | /opt/intel/oneapi/mpi/2021.6.0/lib/libmpicxx.so
-- Python        | ON
--   EXE         | /home/y00648680/python3.8/bin/python3
--   INC         | /home/y00648680/python3.8/include/python3.8
--   LIB         | /home/y00648680/python3.8/lib/libpython3.8.so
--   MODULE      | ON
--   DYNAMIC     | OFF
-- Readline      | /usr/lib64/libreadline.so
-- Curses        | /usr/lib64/libcurses.so;/usr/lib64/libform.so
-- RX3D          | OFF
-- Interviews    | OFF
-- CoreNEURON    | ON
--   PATH        | /home/yjy/nrn/external/coreneuron
--   LINK FLAGS  | -Lx86_64 -lcorenrnmech -L/home/yjy/CaliperInstall/lib64 -lcaliper
--   Legacy Units| OFF
-- Tests         | OFF
-- Profiling     | ON
--   Caliper     | /home/yjy/CaliperInstall/share/cmake/caliper
-- --------------+--------------------------------------------------------------
--  See documentation : https://www.neuron.yale.edu/neuron/

**Is it necessary to set  -DNRN_ENABLE_TESTS=ON?** if not, what's wrong for me ? Thanks for your help!

**Comment by Kim1230** [comment]
It seems that generating special doesn't link to the caliper. Hope for your help

**Comment by pramodk** [comment]
```console
It seems that generating special doesn't link to the caliper.
....
And
./x86_64/special: error while loading shared libraries: libcaliper.so.2: cannot open shared object file: No such file or directory
./x86_64/special: error while loading shared libraries: libcaliper.so.2: cannot open shared object file: No such file or directory
```

Could you do `ldd special-core` as well? (special-core is coreneuron-specific binary generated under x86_64 dir).

If you are seeing ` libcaliper.so.2: cannot open shared object file`, can you try putting right `export LD_LIBRARY_PATH=<caliper-path>/lib64:$LD_LIBRARY_PATH ` env variable and try again `ldd` or running the executable?

**Comment by Kim1230** [comment]
Thanks for your response.
ldd special-core is shown below:
  linux-vdso.so.1 (0x00007ffdb7e51000)
        libcorenrnmech.so => /home/yjy/ringtest-master/./x86_64/libcorenrnmech.so (0x000014d17cbaf000)
        libcoreneuron.so => /home/yjy/nrn_CPU_Capiler/lib/libcoreneuron.so (0x000014d17c9c3000)
        libmpicxx.so.12 => /opt/intel/oneapi/mpi/2021.6.0//lib/libmpicxx.so.12 (0x000014d17c7a3000)
        libmpifort.so.12 => /opt/intel/oneapi/mpi/2021.6.0//lib/libmpifort.so.12 (0x000014d17c3ed000)
        libmpi.so.12 => /opt/intel/oneapi/mpi/2021.6.0//lib/release/libmpi.so.12 (0x000014d17aba5000)
        libdl.so.2 => /lib64/libdl.so.2 (0x000014d17ab89000)
        librt.so.1 => /lib64/librt.so.1 (0x000014d17ab7e000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x000014d17ab5d000)
        libcaliper.so.2 => /home/yjy/CaliperInstall/lib64/libcaliper.so.2 (0x000014d17a655000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x000014d17a4a0000)
        libm.so.6 => /lib64/libm.so.6 (0x000014d17a31d000)
        libiomp5.so => /opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin/libiomp5.so (0x000014d179ee4000)
        libc.so.6 => /lib64/libc.so.6 (0x000014d179d2c000)
        libimf.so => /opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin/libimf.so (0x000014d17969e000)
        libsvml.so => /opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin/libsvml.so (0x000014d17763c000)
        libirng.so => /opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin/libirng.so (0x000014d1772d2000)
        libintlc.so.5 => /opt/intel/oneapi/compiler/2022.1.0/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x000014d17705a000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x000014d177041000)
        /lib64/ld-linux-x86-64.so.2 (0x000014d17cbc4000)
And when I export LD_LIBRARY_PATH=<caliper-path>/lib64:$LD_LIBRARY_PATH. It works! 
Thanks a lot!
