### ISSUE TITLE
add ETA to progressbar

### ISSUE THREAD

**Issue by orena1** [BlueBrain/CoreNeuron#86]
Currently when the simulation runs, the outputs is in the following format:
Completed 0.59, t = 891
It will be beneficial to also add to this output a ETA.

Thanks.

**Comment by pramodk** [comment]
@orena1 :   fixed by #87. 
![screen shot 2018-04-30 at 11 38 23](https://user-images.githubusercontent.com/666852/39421810-0d23b172-4c6b-11e8-9cea-46f0e39f479c.png)
