### ISSUE TITLE
Events with negative delivery time

### ISSUE THREAD

**Issue by brunomaga** [BlueBrain/CoreNeuron#9]
Hi Michael @nrnhines 

When running the `MiniColumn_0` circuit (PCP recipe and config), I get several events with a negative delivery time (see [1s.txt](https://github.com/BlueBrain/CoreNeuron/files/816802/1s.txt) for details).

Backtracing I see the following:
- The event is of type `VecPlayContinuous`
- this is where the event is added
```
  void VecPlayContinuous::play_init() 
  { 
     [...] 
     e_->send((*t_)[ubound_index_], net_cvode_instance, nt);
     [...]
  }
```
- the vector `IvocVect *t` constains negative values.
- the data in `*t` is populated by `nrn_setup.c` at:
```
        F.read_array<double>(vector_vec(yvec), sz);
        IvocVect* tvec = vector_new1(sz);
        F.read_array<double>(vector_vec(tvec), sz);
```
- the `read_array` operation reads the input from the file
- adding the following check after the read-out triggers an assert error:
```
        for (int ii=0; i<tvec->size(); i++)
          { assert(tvec->data()[ii]>=0); }
```
- this is read from the input file that neuron writes, so I believe the issue is there.

Let me know.
Thanks 
Bruno

**Comment by pramodk** [comment]
@brunomaga : you discussed this with Michael. Is this still an issue?

**Comment by pramodk** [comment]
This was due to using forwardskip command line option with negative time. closing.

**Comment by delalond** [comment]
​I would suggest we add a check to the command line, checking the parameter ?

________________________________

**Comment by pramodk** [comment]
agree, PR #15 from Michael will address invalid command line options/values.
