### ISSUE TITLE
If hard disk is full no error message is shown when trying to write out.dat file

### ISSUE THREAD

**Issue by orena1** [BlueBrain/CoreNeuron#91]
It seems that if the harddrive got full while the simulation was running, the simulation ends normally even though the out.dat file was not written correctly.
I think it might be good that CoreNeuron will print an error message stating that the out.dat file was not written completely and if possible to also state that it is because there is no available storage.

Thanks.

**Comment by pramodk** [comment]
Hi Oren,

Could you point us to the job output? In case of error while writing spike output I expect error message `Error while writing spike output`.

**Comment by orena1** [comment]
Sorry I deleted the directory.

**Comment by tapaswenipathak** [comment]
Hi @orena1 @pramodk, do you think this ticket can be closed?

**Comment by pramodk** [comment]
yes..I expect this is already handled by [this](https://github.com/BlueBrain/CoreNeuron/blob/d8a235a54b6ed8a3c39d14c31a5da79dcece57c2/coreneuron/nrniv/output_spikes.cpp#L199).
