### ISSUE TITLE
--read-config option message 

### ISSUE THREAD

**Issue by fouriaux** [BlueBrain/CoreNeuron#93]
When using --read-arg with a non-default name for the config file, an information message appears which seems unclear about what information it provides.
```
>coreneuron_exec --read-config 1.conf
Info: No default arguments file provided: config
```

**Comment by iomaganaris** [comment]
@nrnhines  : I am trying to solve small open issues. I am wondering about below code from [here](https://github.com/BlueBrain/CoreNeuron/blob/cab134dad540feafae9b78f2aca2fff70cc25248/coreneuron/nrniv/nrnoptarg.cpp#L163):

```
    // last the default config file
    std::string cfg("config");
    if (!opt->importFile(cfg.c_str(), '#')) {
        if (nrnmpi_myid == 0)
            std::cerr << "Info: No default arguments file provided: " << cfg << std::endl;
    } else {
        if (nrnmpi_myid == 0)
            std::cout << "Read default configuration file: " << cfg << std::endl;
    }
```

As we are providing config file to `--read-config`, do we need to check `config` file? Is that needed?
