### ISSUE TITLE
Report reading configuration 

### ISSUE THREAD

**Issue by fouriaux** [BlueBrain/CoreNeuron#94]
1. Wrong error message when trying to read a configuration file that does not exist or cannot be opened:
"Error while reading report configuration "
This is to be replaced with meaningful message.

**Comment by tapaswenipathak** [comment]
Hi @fouriaux @pramodk, I think this requires message replacement by some other message, do you have more meaningful message in mind? 

Would `report: config: reading a config file that does not exist or cannot be opened` is something you would prefer?  Or you would like a check on if the file exist or if the file can be opened and then separate message per check?

**Comment by tapaswenipathak** [comment]
Hi @fouriaux @pramodk, do you have more meaningful message in mind?

**Comment by pramodk** [comment]
It seems like this is already fixed [here](https://github.com/BlueBrain/CoreNeuron/blob/d8a235a54b6ed8a3c39d14c31a5da79dcece57c2/coreneuron/utils/reports/report_configuration_parser.cpp#L70).

**Comment by tapaswenipathak** [comment]
Yeah can be closed I think.
